version: "2"
services:
  web:
    build: .
    command: echo "edit docker-compose.yml with your startup command"
    labels:
      - convox.port.443.protocol=tls
      - convox.port.443.proxy=true
    ports:
      - 80:4000
      - 443:4001
