// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT.

package rdsiface_test

import (
	"testing"

	"github.com/convox/kernel/Godeps/_workspace/src/github.com/aws/aws-sdk-go/service/rds"
	"github.com/convox/kernel/Godeps/_workspace/src/github.com/aws/aws-sdk-go/service/rds/rdsiface"
	"github.com/convox/kernel/Godeps/_workspace/src/github.com/stretchr/testify/assert"
)

func TestInterface(t *testing.T) {
	assert.Implements(t, (*rdsiface.RDSAPI)(nil), rds.New(nil))
}
