version: "2"
services:
  web:
    build: .
    environment:
      - SECRET_KEY
    labels:
      - convox.port.443.protocol=tls
      - convox.port.443.proxy=true
    links:
      - database
    ports:
      - 80:4000
      - 443:4001
  database:
    image: convox/postgres
    ports:
      - 5432
