version: 2
jobs:
  build:
    parallelism: 3
    docker:
      - image: circleci/golang:1.9.2
    steps:
      - checkout
      - run: ci/dependencies-pre.sh
      - run: ci/install.sh
      - run: ci/tests/example-app django
      - run: ci/tests/example-app node-workers
      - run:
          command: ci/tests/example-app rails
          no_output_timeout: 20m
      - run: ci/report.sh
      - run: ci/uninstall.sh
      - run: ci/cleanup.sh
      - store_artifacts:
          path: /tmp/artifacts
