version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:1.9.2
    steps:
      - checkout
      - run: ci/dependencies-pre.sh
      - run: ci/install.sh
      - run: ci/tests/example-app django
      - run: ci/tests/example-app node-workers
      - run: ci/tests/example-app rails
      - run: ci/report.sh
      - run: ci/uninstall.sh
      - run: ci/cleanup.sh
