[[constraint]]
  name = "github.com/cheggaaa/pb"
  version = "1.0.18"

[[constraint]]
  name = "github.com/docker/go-units"
  version = "0.3.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.1.3"

[[constraint]]
  name = "gopkg.in/urfave/cli.v1"
  version = "1.19.1"
