
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  branch = "master"
  name = "github.com/Azure/go-ansiterm"

[[constraint]]
  name = "github.com/aryann/difflib"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"

[[constraint]]
  name = "github.com/briandowns/spinner"

[[constraint]]
  name = "github.com/cheggaaa/pb"

[[constraint]]
  name = "github.com/cloudflare/cfssl"

[[constraint]]
  name = "github.com/codegangsta/negroni"

[[constraint]]
  branch = "master"
  name = "github.com/convox/inotify"

[[constraint]]
  branch = "master"
  name = "github.com/convox/logger"

[[constraint]]
  name = "github.com/convox/nlogger"

[[constraint]]
  branch = "master"
  name = "github.com/convox/version"

[[constraint]]
  name = "github.com/ddollar/logger"

[[constraint]]
  name = "github.com/docker/docker"

[[constraint]]
  name = "github.com/docker/go-units"
  version = "0.3.0"

[[constraint]]
  name = "github.com/dustin/go-humanize"

[[constraint]]
  name = "github.com/equinox-io/equinox"

[[constraint]]
  name = "github.com/fatih/color"

[[constraint]]
  name = "github.com/fluent/fluent-logger-golang"

[[constraint]]
  name = "github.com/fsouza/go-dockerclient"

[[constraint]]
  name = "github.com/gorilla/mux"

[[constraint]]
  branch = "master"
  name = "github.com/jasonmoo/lambda_proc"

[[constraint]]
  branch = "master"
  name = "github.com/kballard/go-shellquote"

[[constraint]]
  name = "github.com/mitchellh/go-homedir"

[[constraint]]
  name = "github.com/mweagle/Sparta"

[[constraint]]
  name = "github.com/segmentio/analytics-go"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.1.3"

[[constraint]]
  name = "github.com/stvp/rollbar"

[[constraint]]
  name = "github.com/twmb/algoimpl"

[[constraint]]
  name = "golang.org/x/crypto"

[[constraint]]
  name = "golang.org/x/net"

[[constraint]]
  name = "gopkg.in/urfave/cli.v1"
  version = "1.19.1"

[[constraint]]
  name = "gopkg.in/yaml.v2"
