required = [
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/defaulter-gen",
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/go-to-protobuf/protoc-gen-gogo",
  "k8s.io/code-generator/cmd/import-boss",
  "k8s.io/code-generator/cmd/openapi-gen",
  "k8s.io/code-generator/cmd/set-gen"
]

[prune]
  non-go = true
  go-tests = true
  unused-packages = true

  [[prune.project]]
    name = "k8s.io/code-generator"
    non-go = false
    unused-packages = false

[[override]]
  name = "gopkg.in/yaml.v2"
  source = "github.com/ddollar/yaml"
  branch = "merge-map-slice"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.11.0"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.11.0"

[[constraint]]
  name = "k8s.io/client-go"
  version = "8.0.0"

[[constraint]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.11.0"

[[constraint]]
  name = "k8s.io/metrics"
  version = "kubernetes-1.11.0"
