// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT.

package sqsiface_test

import (
	"testing"

	"github.com/convox/kernel/Godeps/_workspace/src/github.com/aws/aws-sdk-go/service/sqs"
	"github.com/convox/kernel/Godeps/_workspace/src/github.com/aws/aws-sdk-go/service/sqs/sqsiface"
	"github.com/convox/kernel/Godeps/_workspace/src/github.com/stretchr/testify/assert"
)

func TestInterface(t *testing.T) {
	assert.Implements(t, (*sqsiface.SQSAPI)(nil), sqs.New(nil))
}
