/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v2 "github.com/convox/rack/pkg/atom/pkg/apis/convox/v2"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeAtoms implements AtomInterface
type FakeAtoms struct {
	Fake *FakeConvoxV2
	ns   string
}

var atomsResource = schema.GroupVersionResource{Group: "convox.com", Version: "v2", Resource: "atoms"}

var atomsKind = schema.GroupVersionKind{Group: "convox.com", Version: "v2", Kind: "Atom"}

// Get takes name of the atom, and returns the corresponding atom object, and an error if there is any.
func (c *FakeAtoms) Get(name string, options v1.GetOptions) (result *v2.Atom, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(atomsResource, c.ns, name), &v2.Atom{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v2.Atom), err
}

// List takes label and field selectors, and returns the list of Atoms that match those selectors.
func (c *FakeAtoms) List(opts v1.ListOptions) (result *v2.AtomList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(atomsResource, atomsKind, c.ns, opts), &v2.AtomList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v2.AtomList{ListMeta: obj.(*v2.AtomList).ListMeta}
	for _, item := range obj.(*v2.AtomList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested atoms.
func (c *FakeAtoms) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(atomsResource, c.ns, opts))

}

// Create takes the representation of a atom and creates it.  Returns the server's representation of the atom, and an error, if there is any.
func (c *FakeAtoms) Create(atom *v2.Atom) (result *v2.Atom, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(atomsResource, c.ns, atom), &v2.Atom{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v2.Atom), err
}

// Update takes the representation of a atom and updates it. Returns the server's representation of the atom, and an error, if there is any.
func (c *FakeAtoms) Update(atom *v2.Atom) (result *v2.Atom, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(atomsResource, c.ns, atom), &v2.Atom{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v2.Atom), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeAtoms) UpdateStatus(atom *v2.Atom) (*v2.Atom, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(atomsResource, "status", c.ns, atom), &v2.Atom{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v2.Atom), err
}

// Delete takes name of the atom and deletes it. Returns an error if one occurs.
func (c *FakeAtoms) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(atomsResource, c.ns, name), &v2.Atom{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAtoms) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(atomsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v2.AtomList{})
	return err
}

// Patch applies the patch and returns the patched atom.
func (c *FakeAtoms) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v2.Atom, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(atomsResource, c.ns, name, data, subresources...), &v2.Atom{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v2.Atom), err
}
