/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/convox/rack/provider/k8s/pkg/apis/convox/v1"
	scheme "github.com/convox/rack/provider/k8s/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ExternalResourcesGetter has a method to return a ExternalResourceInterface.
// A group's client should implement this interface.
type ExternalResourcesGetter interface {
	ExternalResources(namespace string) ExternalResourceInterface
}

// ExternalResourceInterface has methods to work with ExternalResource resources.
type ExternalResourceInterface interface {
	Create(*v1.ExternalResource) (*v1.ExternalResource, error)
	Update(*v1.ExternalResource) (*v1.ExternalResource, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.ExternalResource, error)
	List(opts metav1.ListOptions) (*v1.ExternalResourceList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.ExternalResource, err error)
	ExternalResourceExpansion
}

// externalResources implements ExternalResourceInterface
type externalResources struct {
	client rest.Interface
	ns     string
}

// newExternalResources returns a ExternalResources
func newExternalResources(c *ConvoxV1Client, namespace string) *externalResources {
	return &externalResources{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the externalResource, and returns the corresponding externalResource object, and an error if there is any.
func (c *externalResources) Get(name string, options metav1.GetOptions) (result *v1.ExternalResource, err error) {
	result = &v1.ExternalResource{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("externalresources").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ExternalResources that match those selectors.
func (c *externalResources) List(opts metav1.ListOptions) (result *v1.ExternalResourceList, err error) {
	result = &v1.ExternalResourceList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("externalresources").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested externalResources.
func (c *externalResources) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("externalresources").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a externalResource and creates it.  Returns the server's representation of the externalResource, and an error, if there is any.
func (c *externalResources) Create(externalResource *v1.ExternalResource) (result *v1.ExternalResource, err error) {
	result = &v1.ExternalResource{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("externalresources").
		Body(externalResource).
		Do().
		Into(result)
	return
}

// Update takes the representation of a externalResource and updates it. Returns the server's representation of the externalResource, and an error, if there is any.
func (c *externalResources) Update(externalResource *v1.ExternalResource) (result *v1.ExternalResource, err error) {
	result = &v1.ExternalResource{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("externalresources").
		Name(externalResource.Name).
		Body(externalResource).
		Do().
		Into(result)
	return
}

// Delete takes name of the externalResource and deletes it. Returns an error if one occurs.
func (c *externalResources) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("externalresources").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *externalResources) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("externalresources").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched externalResource.
func (c *externalResources) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.ExternalResource, err error) {
	result = &v1.ExternalResource{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("externalresources").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
