resources:
  postgres:
    type: postgres
    options:
      class: db.t3.micro
      version: 14
  mysql:
    type: mysql
    options:
      class: db.t3.micro
  mariadb:
    type: mariadb
    options:
      class: db.t3.micro
      version: 10.6
  memcached:
    type: memcached
  redis:
    type: redis
  sharedvolume:
    type: efs
    options:
      path: "/app/httpd"
services:
  web:
    build: .
    port: 80
    volumes:
      # Persistent volumes
      - /my/shared/data
      - /var/www/html
      # Host Volumes
      - /sys/fs/cgroup/:/host/sys/fs/cgroup/
      - /proc/:/host/proc/
      - /var/run/docker.sock:/var/run/docker.sock
      # EFS Resource (shared volumes)
      - sharedvolume:/app/httpd
    resources:
      - postgres
      - mysql
      - mariadb
      - memcached
      - redis
      - sharedvolume
timers:
  example:
    command: /usr/local/apache2/timer-cmd.sh
    schedule: "*/1 * * * ?"
    service: web
