/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	time "time"

	convoxv1 "github.com/convox/rack/provider/k8s/pkg/apis/convox/v1"
	versioned "github.com/convox/rack/provider/k8s/pkg/client/clientset/versioned"
	internalinterfaces "github.com/convox/rack/provider/k8s/pkg/client/informers/externalversions/internalinterfaces"
	v1 "github.com/convox/rack/provider/k8s/pkg/client/listers/convox/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ExternalResourceInformer provides access to a shared informer and lister for
// ExternalResources.
type ExternalResourceInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.ExternalResourceLister
}

type externalResourceInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewExternalResourceInformer constructs a new informer for ExternalResource type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewExternalResourceInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredExternalResourceInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredExternalResourceInformer constructs a new informer for ExternalResource type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredExternalResourceInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ConvoxV1().ExternalResources(namespace).List(options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ConvoxV1().ExternalResources(namespace).Watch(options)
			},
		},
		&convoxv1.ExternalResource{},
		resyncPeriod,
		indexers,
	)
}

func (f *externalResourceInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredExternalResourceInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *externalResourceInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&convoxv1.ExternalResource{}, f.defaultInformer)
}

func (f *externalResourceInformer) Lister() v1.ExternalResourceLister {
	return v1.NewExternalResourceLister(f.Informer().GetIndexer())
}
