/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	time "time"

	convoxv1 "github.com/convox/rack/provider/k8s/pkg/apis/convox/v1"
	versioned "github.com/convox/rack/provider/k8s/pkg/client/clientset/versioned"
	internalinterfaces "github.com/convox/rack/provider/k8s/pkg/client/informers/externalversions/internalinterfaces"
	v1 "github.com/convox/rack/provider/k8s/pkg/client/listers/convox/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ReleaseInformer provides access to a shared informer and lister for
// Releases.
type ReleaseInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.ReleaseLister
}

type releaseInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewReleaseInformer constructs a new informer for Release type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewReleaseInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredReleaseInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredReleaseInformer constructs a new informer for Release type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredReleaseInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ConvoxV1().Releases(namespace).List(options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ConvoxV1().Releases(namespace).Watch(options)
			},
		},
		&convoxv1.Release{},
		resyncPeriod,
		indexers,
	)
}

func (f *releaseInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredReleaseInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *releaseInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&convoxv1.Release{}, f.defaultInformer)
}

func (f *releaseInformer) Lister() v1.ReleaseLister {
	return v1.NewReleaseLister(f.Informer().GetIndexer())
}
