/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	convoxv1 "github.com/convox/rack/pkg/atom/pkg/apis/convox/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeParticles implements ParticleInterface
type FakeParticles struct {
	Fake *FakeConvoxV1
	ns   string
}

var particlesResource = schema.GroupVersionResource{Group: "convox.com", Version: "v1", Resource: "particles"}

var particlesKind = schema.GroupVersionKind{Group: "convox.com", Version: "v1", Kind: "Particle"}

// Get takes name of the particle, and returns the corresponding particle object, and an error if there is any.
func (c *FakeParticles) Get(name string, options v1.GetOptions) (result *convoxv1.Particle, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(particlesResource, c.ns, name), &convoxv1.Particle{})

	if obj == nil {
		return nil, err
	}
	return obj.(*convoxv1.Particle), err
}

// List takes label and field selectors, and returns the list of Particles that match those selectors.
func (c *FakeParticles) List(opts v1.ListOptions) (result *convoxv1.ParticleList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(particlesResource, particlesKind, c.ns, opts), &convoxv1.ParticleList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &convoxv1.ParticleList{ListMeta: obj.(*convoxv1.ParticleList).ListMeta}
	for _, item := range obj.(*convoxv1.ParticleList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested particles.
func (c *FakeParticles) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(particlesResource, c.ns, opts))

}

// Create takes the representation of a particle and creates it.  Returns the server's representation of the particle, and an error, if there is any.
func (c *FakeParticles) Create(particle *convoxv1.Particle) (result *convoxv1.Particle, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(particlesResource, c.ns, particle), &convoxv1.Particle{})

	if obj == nil {
		return nil, err
	}
	return obj.(*convoxv1.Particle), err
}

// Update takes the representation of a particle and updates it. Returns the server's representation of the particle, and an error, if there is any.
func (c *FakeParticles) Update(particle *convoxv1.Particle) (result *convoxv1.Particle, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(particlesResource, c.ns, particle), &convoxv1.Particle{})

	if obj == nil {
		return nil, err
	}
	return obj.(*convoxv1.Particle), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeParticles) UpdateStatus(particle *convoxv1.Particle) (*convoxv1.Particle, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(particlesResource, "status", c.ns, particle), &convoxv1.Particle{})

	if obj == nil {
		return nil, err
	}
	return obj.(*convoxv1.Particle), err
}

// Delete takes name of the particle and deletes it. Returns an error if one occurs.
func (c *FakeParticles) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(particlesResource, c.ns, name), &convoxv1.Particle{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeParticles) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(particlesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &convoxv1.ParticleList{})
	return err
}

// Patch applies the patch and returns the patched particle.
func (c *FakeParticles) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *convoxv1.Particle, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(particlesResource, c.ns, name, data, subresources...), &convoxv1.Particle{})

	if obj == nil {
		return nil, err
	}
	return obj.(*convoxv1.Particle), err
}
