/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	convoxv1 "github.com/convox/rack/pkg/atom/pkg/apis/convox/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeAtomTemplates implements AtomTemplateInterface
type FakeAtomTemplates struct {
	Fake *FakeConvoxV1
	ns   string
}

var atomtemplatesResource = schema.GroupVersionResource{Group: "convox.com", Version: "v1", Resource: "atomtemplates"}

var atomtemplatesKind = schema.GroupVersionKind{Group: "convox.com", Version: "v1", Kind: "AtomTemplate"}

// Get takes name of the atomTemplate, and returns the corresponding atomTemplate object, and an error if there is any.
func (c *FakeAtomTemplates) Get(name string, options v1.GetOptions) (result *convoxv1.AtomTemplate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(atomtemplatesResource, c.ns, name), &convoxv1.AtomTemplate{})

	if obj == nil {
		return nil, err
	}
	return obj.(*convoxv1.AtomTemplate), err
}

// List takes label and field selectors, and returns the list of AtomTemplates that match those selectors.
func (c *FakeAtomTemplates) List(opts v1.ListOptions) (result *convoxv1.AtomTemplateList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(atomtemplatesResource, atomtemplatesKind, c.ns, opts), &convoxv1.AtomTemplateList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &convoxv1.AtomTemplateList{ListMeta: obj.(*convoxv1.AtomTemplateList).ListMeta}
	for _, item := range obj.(*convoxv1.AtomTemplateList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested atomTemplates.
func (c *FakeAtomTemplates) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(atomtemplatesResource, c.ns, opts))

}

// Create takes the representation of a atomTemplate and creates it.  Returns the server's representation of the atomTemplate, and an error, if there is any.
func (c *FakeAtomTemplates) Create(atomTemplate *convoxv1.AtomTemplate) (result *convoxv1.AtomTemplate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(atomtemplatesResource, c.ns, atomTemplate), &convoxv1.AtomTemplate{})

	if obj == nil {
		return nil, err
	}
	return obj.(*convoxv1.AtomTemplate), err
}

// Update takes the representation of a atomTemplate and updates it. Returns the server's representation of the atomTemplate, and an error, if there is any.
func (c *FakeAtomTemplates) Update(atomTemplate *convoxv1.AtomTemplate) (result *convoxv1.AtomTemplate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(atomtemplatesResource, c.ns, atomTemplate), &convoxv1.AtomTemplate{})

	if obj == nil {
		return nil, err
	}
	return obj.(*convoxv1.AtomTemplate), err
}

// Delete takes name of the atomTemplate and deletes it. Returns an error if one occurs.
func (c *FakeAtomTemplates) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(atomtemplatesResource, c.ns, name), &convoxv1.AtomTemplate{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAtomTemplates) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(atomtemplatesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &convoxv1.AtomTemplateList{})
	return err
}

// Patch applies the patch and returns the patched atomTemplate.
func (c *FakeAtomTemplates) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *convoxv1.AtomTemplate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(atomtemplatesResource, c.ns, name, data, subresources...), &convoxv1.AtomTemplate{})

	if obj == nil {
		return nil, err
	}
	return obj.(*convoxv1.AtomTemplate), err
}
