#!/bin/bash
set -ex -o pipefail

# Running locally:
#
#   export CIRCLE_ARTIFACTS=/tmp/
#   export CIRCLE_BUILD_NUM=0
#   ./ci/tests/example-apps

parallel --joblog $CIRCLE_ARTIFACTS/parallel.log --line-buffer --results $CIRCLE_ARTIFACTS --tag ./ci/tests/example-app {} ::: null rails django