#!/bin/bash
set -ex -o pipefail

# HACK: example-apps `parallel` wrapper, and its different stdin behavior for first process
[[ $1 == null ]] && exit 0

export EXAMPLE_NAME=$1

# inferred
export CIRCLE_ARTIFACTS=${CIRCLE_ARTIFACTS:-/tmp/artifacts}
export CIRCLE_BUILD_NUM=${CIRCLE_BUILD_NUM:-0}
export APP_NAME=${EXAMPLE_NAME}-${CIRCLE_BUILD_NUM}
export STACK_NAME=convox-${CIRCLE_BUILD_NUM}

git clone https://github.com/convox-examples/${EXAMPLE_NAME}.git
cd ${EXAMPLE_NAME}

if [[ "$EXAMPLE_NAME" == "rails" ]]; then
  convox apps create $APP_NAME --wait --generation 2
else
  convox apps create $APP_NAME --wait
fi

convox deploy --app $APP_NAME --wait

convox apps info --app $APP_NAME

convox scale web --count 2 --memory 128 --app $APP_NAME --wait

balancer=$(convox api get /apps/$APP_NAME/formation | jq -r '.[] | select(.name == "web" and .ports[] == 443) | .balancer')

# While the following curl call would work:
# curl -vi -m2 --retry 60 --retry-delay 20 -k https://$balancer
# ran into an issue where curl would return "curl: (52) Empty reply from server" with no easy way to retry
c=0
while ! curl -m2 $balancer; do
  let c=c+1
  [ $c -gt 60 ] && exit 1

  sleep 20
done

convox ps --stats --app $APP_NAME

convox run --app $APP_NAME web 'bin/test || true'

convox logs --app $APP_NAME --follow=false --since=25m
