// Code generated by mockery v1.0.0. DO NOT EDIT.

package aws

import (
	cloudwatch "github.com/aws/aws-sdk-go/service/cloudwatch"

	context "context"

	mock "github.com/stretchr/testify/mock"

	request "github.com/aws/aws-sdk-go/aws/request"
)

// CloudWatchAPI is an autogenerated mock type for the CloudWatchAPI type
type CloudWatchAPI struct {
	mock.Mock
}

// DeleteAlarms provides a mock function with given fields: _a0
func (_m *CloudWatchAPI) DeleteAlarms(_a0 *cloudwatch.DeleteAlarmsInput) (*cloudwatch.DeleteAlarmsOutput, error) {
	ret := _m.Called(_a0)

	var r0 *cloudwatch.DeleteAlarmsOutput
	if rf, ok := ret.Get(0).(func(*cloudwatch.DeleteAlarmsInput) *cloudwatch.DeleteAlarmsOutput); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cloudwatch.DeleteAlarmsOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*cloudwatch.DeleteAlarmsInput) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteAlarmsRequest provides a mock function with given fields: _a0
func (_m *CloudWatchAPI) DeleteAlarmsRequest(_a0 *cloudwatch.DeleteAlarmsInput) (*request.Request, *cloudwatch.DeleteAlarmsOutput) {
	ret := _m.Called(_a0)

	var r0 *request.Request
	if rf, ok := ret.Get(0).(func(*cloudwatch.DeleteAlarmsInput) *request.Request); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*request.Request)
		}
	}

	var r1 *cloudwatch.DeleteAlarmsOutput
	if rf, ok := ret.Get(1).(func(*cloudwatch.DeleteAlarmsInput) *cloudwatch.DeleteAlarmsOutput); ok {
		r1 = rf(_a0)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*cloudwatch.DeleteAlarmsOutput)
		}
	}

	return r0, r1
}

// DeleteAlarmsWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *CloudWatchAPI) DeleteAlarmsWithContext(_a0 context.Context, _a1 *cloudwatch.DeleteAlarmsInput, _a2 ...request.Option) (*cloudwatch.DeleteAlarmsOutput, error) {
	_va := make([]interface{}, len(_a2))
	for _i := range _a2 {
		_va[_i] = _a2[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _a0, _a1)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *cloudwatch.DeleteAlarmsOutput
	if rf, ok := ret.Get(0).(func(context.Context, *cloudwatch.DeleteAlarmsInput, ...request.Option) *cloudwatch.DeleteAlarmsOutput); ok {
		r0 = rf(_a0, _a1, _a2...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cloudwatch.DeleteAlarmsOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *cloudwatch.DeleteAlarmsInput, ...request.Option) error); ok {
		r1 = rf(_a0, _a1, _a2...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteAnomalyDetector provides a mock function with given fields: _a0
func (_m *CloudWatchAPI) DeleteAnomalyDetector(_a0 *cloudwatch.DeleteAnomalyDetectorInput) (*cloudwatch.DeleteAnomalyDetectorOutput, error) {
	ret := _m.Called(_a0)

	var r0 *cloudwatch.DeleteAnomalyDetectorOutput
	if rf, ok := ret.Get(0).(func(*cloudwatch.DeleteAnomalyDetectorInput) *cloudwatch.DeleteAnomalyDetectorOutput); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cloudwatch.DeleteAnomalyDetectorOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*cloudwatch.DeleteAnomalyDetectorInput) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteAnomalyDetectorRequest provides a mock function with given fields: _a0
func (_m *CloudWatchAPI) DeleteAnomalyDetectorRequest(_a0 *cloudwatch.DeleteAnomalyDetectorInput) (*request.Request, *cloudwatch.DeleteAnomalyDetectorOutput) {
	ret := _m.Called(_a0)

	var r0 *request.Request
	if rf, ok := ret.Get(0).(func(*cloudwatch.DeleteAnomalyDetectorInput) *request.Request); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*request.Request)
		}
	}

	var r1 *cloudwatch.DeleteAnomalyDetectorOutput
	if rf, ok := ret.Get(1).(func(*cloudwatch.DeleteAnomalyDetectorInput) *cloudwatch.DeleteAnomalyDetectorOutput); ok {
		r1 = rf(_a0)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*cloudwatch.DeleteAnomalyDetectorOutput)
		}
	}

	return r0, r1
}

// DeleteAnomalyDetectorWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *CloudWatchAPI) DeleteAnomalyDetectorWithContext(_a0 context.Context, _a1 *cloudwatch.DeleteAnomalyDetectorInput, _a2 ...request.Option) (*cloudwatch.DeleteAnomalyDetectorOutput, error) {
	_va := make([]interface{}, len(_a2))
	for _i := range _a2 {
		_va[_i] = _a2[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _a0, _a1)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *cloudwatch.DeleteAnomalyDetectorOutput
	if rf, ok := ret.Get(0).(func(context.Context, *cloudwatch.DeleteAnomalyDetectorInput, ...request.Option) *cloudwatch.DeleteAnomalyDetectorOutput); ok {
		r0 = rf(_a0, _a1, _a2...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cloudwatch.DeleteAnomalyDetectorOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *cloudwatch.DeleteAnomalyDetectorInput, ...request.Option) error); ok {
		r1 = rf(_a0, _a1, _a2...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteDashboards provides a mock function with given fields: _a0
func (_m *CloudWatchAPI) DeleteDashboards(_a0 *cloudwatch.DeleteDashboardsInput) (*cloudwatch.DeleteDashboardsOutput, error) {
	ret := _m.Called(_a0)

	var r0 *cloudwatch.DeleteDashboardsOutput
	if rf, ok := ret.Get(0).(func(*cloudwatch.DeleteDashboardsInput) *cloudwatch.DeleteDashboardsOutput); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cloudwatch.DeleteDashboardsOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*cloudwatch.DeleteDashboardsInput) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteDashboardsRequest provides a mock function with given fields: _a0
func (_m *CloudWatchAPI) DeleteDashboardsRequest(_a0 *cloudwatch.DeleteDashboardsInput) (*request.Request, *cloudwatch.DeleteDashboardsOutput) {
	ret := _m.Called(_a0)

	var r0 *request.Request
	if rf, ok := ret.Get(0).(func(*cloudwatch.DeleteDashboardsInput) *request.Request); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*request.Request)
		}
	}

	var r1 *cloudwatch.DeleteDashboardsOutput
	if rf, ok := ret.Get(1).(func(*cloudwatch.DeleteDashboardsInput) *cloudwatch.DeleteDashboardsOutput); ok {
		r1 = rf(_a0)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*cloudwatch.DeleteDashboardsOutput)
		}
	}

	return r0, r1
}

// DeleteDashboardsWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *CloudWatchAPI) DeleteDashboardsWithContext(_a0 context.Context, _a1 *cloudwatch.DeleteDashboardsInput, _a2 ...request.Option) (*cloudwatch.DeleteDashboardsOutput, error) {
	_va := make([]interface{}, len(_a2))
	for _i := range _a2 {
		_va[_i] = _a2[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _a0, _a1)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *cloudwatch.DeleteDashboardsOutput
	if rf, ok := ret.Get(0).(func(context.Context, *cloudwatch.DeleteDashboardsInput, ...request.Option) *cloudwatch.DeleteDashboardsOutput); ok {
		r0 = rf(_a0, _a1, _a2...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cloudwatch.DeleteDashboardsOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *cloudwatch.DeleteDashboardsInput, ...request.Option) error); ok {
		r1 = rf(_a0, _a1, _a2...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DescribeAlarmHistory provides a mock function with given fields: _a0
func (_m *CloudWatchAPI) DescribeAlarmHistory(_a0 *cloudwatch.DescribeAlarmHistoryInput) (*cloudwatch.DescribeAlarmHistoryOutput, error) {
	ret := _m.Called(_a0)

	var r0 *cloudwatch.DescribeAlarmHistoryOutput
	if rf, ok := ret.Get(0).(func(*cloudwatch.DescribeAlarmHistoryInput) *cloudwatch.DescribeAlarmHistoryOutput); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cloudwatch.DescribeAlarmHistoryOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*cloudwatch.DescribeAlarmHistoryInput) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DescribeAlarmHistoryPages provides a mock function with given fields: _a0, _a1
func (_m *CloudWatchAPI) DescribeAlarmHistoryPages(_a0 *cloudwatch.DescribeAlarmHistoryInput, _a1 func(*cloudwatch.DescribeAlarmHistoryOutput, bool) bool) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(*cloudwatch.DescribeAlarmHistoryInput, func(*cloudwatch.DescribeAlarmHistoryOutput, bool) bool) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DescribeAlarmHistoryPagesWithContext provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *CloudWatchAPI) DescribeAlarmHistoryPagesWithContext(_a0 context.Context, _a1 *cloudwatch.DescribeAlarmHistoryInput, _a2 func(*cloudwatch.DescribeAlarmHistoryOutput, bool) bool, _a3 ...request.Option) error {
	_va := make([]interface{}, len(_a3))
	for _i := range _a3 {
		_va[_i] = _a3[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _a0, _a1, _a2)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *cloudwatch.DescribeAlarmHistoryInput, func(*cloudwatch.DescribeAlarmHistoryOutput, bool) bool, ...request.Option) error); ok {
		r0 = rf(_a0, _a1, _a2, _a3...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DescribeAlarmHistoryRequest provides a mock function with given fields: _a0
func (_m *CloudWatchAPI) DescribeAlarmHistoryRequest(_a0 *cloudwatch.DescribeAlarmHistoryInput) (*request.Request, *cloudwatch.DescribeAlarmHistoryOutput) {
	ret := _m.Called(_a0)

	var r0 *request.Request
	if rf, ok := ret.Get(0).(func(*cloudwatch.DescribeAlarmHistoryInput) *request.Request); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*request.Request)
		}
	}

	var r1 *cloudwatch.DescribeAlarmHistoryOutput
	if rf, ok := ret.Get(1).(func(*cloudwatch.DescribeAlarmHistoryInput) *cloudwatch.DescribeAlarmHistoryOutput); ok {
		r1 = rf(_a0)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*cloudwatch.DescribeAlarmHistoryOutput)
		}
	}

	return r0, r1
}

// DescribeAlarmHistoryWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *CloudWatchAPI) DescribeAlarmHistoryWithContext(_a0 context.Context, _a1 *cloudwatch.DescribeAlarmHistoryInput, _a2 ...request.Option) (*cloudwatch.DescribeAlarmHistoryOutput, error) {
	_va := make([]interface{}, len(_a2))
	for _i := range _a2 {
		_va[_i] = _a2[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _a0, _a1)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *cloudwatch.DescribeAlarmHistoryOutput
	if rf, ok := ret.Get(0).(func(context.Context, *cloudwatch.DescribeAlarmHistoryInput, ...request.Option) *cloudwatch.DescribeAlarmHistoryOutput); ok {
		r0 = rf(_a0, _a1, _a2...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cloudwatch.DescribeAlarmHistoryOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *cloudwatch.DescribeAlarmHistoryInput, ...request.Option) error); ok {
		r1 = rf(_a0, _a1, _a2...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DescribeAlarms provides a mock function with given fields: _a0
func (_m *CloudWatchAPI) DescribeAlarms(_a0 *cloudwatch.DescribeAlarmsInput) (*cloudwatch.DescribeAlarmsOutput, error) {
	ret := _m.Called(_a0)

	var r0 *cloudwatch.DescribeAlarmsOutput
	if rf, ok := ret.Get(0).(func(*cloudwatch.DescribeAlarmsInput) *cloudwatch.DescribeAlarmsOutput); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cloudwatch.DescribeAlarmsOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*cloudwatch.DescribeAlarmsInput) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DescribeAlarmsForMetric provides a mock function with given fields: _a0
func (_m *CloudWatchAPI) DescribeAlarmsForMetric(_a0 *cloudwatch.DescribeAlarmsForMetricInput) (*cloudwatch.DescribeAlarmsForMetricOutput, error) {
	ret := _m.Called(_a0)

	var r0 *cloudwatch.DescribeAlarmsForMetricOutput
	if rf, ok := ret.Get(0).(func(*cloudwatch.DescribeAlarmsForMetricInput) *cloudwatch.DescribeAlarmsForMetricOutput); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cloudwatch.DescribeAlarmsForMetricOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*cloudwatch.DescribeAlarmsForMetricInput) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DescribeAlarmsForMetricRequest provides a mock function with given fields: _a0
func (_m *CloudWatchAPI) DescribeAlarmsForMetricRequest(_a0 *cloudwatch.DescribeAlarmsForMetricInput) (*request.Request, *cloudwatch.DescribeAlarmsForMetricOutput) {
	ret := _m.Called(_a0)

	var r0 *request.Request
	if rf, ok := ret.Get(0).(func(*cloudwatch.DescribeAlarmsForMetricInput) *request.Request); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*request.Request)
		}
	}

	var r1 *cloudwatch.DescribeAlarmsForMetricOutput
	if rf, ok := ret.Get(1).(func(*cloudwatch.DescribeAlarmsForMetricInput) *cloudwatch.DescribeAlarmsForMetricOutput); ok {
		r1 = rf(_a0)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*cloudwatch.DescribeAlarmsForMetricOutput)
		}
	}

	return r0, r1
}

// DescribeAlarmsForMetricWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *CloudWatchAPI) DescribeAlarmsForMetricWithContext(_a0 context.Context, _a1 *cloudwatch.DescribeAlarmsForMetricInput, _a2 ...request.Option) (*cloudwatch.DescribeAlarmsForMetricOutput, error) {
	_va := make([]interface{}, len(_a2))
	for _i := range _a2 {
		_va[_i] = _a2[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _a0, _a1)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *cloudwatch.DescribeAlarmsForMetricOutput
	if rf, ok := ret.Get(0).(func(context.Context, *cloudwatch.DescribeAlarmsForMetricInput, ...request.Option) *cloudwatch.DescribeAlarmsForMetricOutput); ok {
		r0 = rf(_a0, _a1, _a2...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cloudwatch.DescribeAlarmsForMetricOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *cloudwatch.DescribeAlarmsForMetricInput, ...request.Option) error); ok {
		r1 = rf(_a0, _a1, _a2...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DescribeAlarmsPages provides a mock function with given fields: _a0, _a1
func (_m *CloudWatchAPI) DescribeAlarmsPages(_a0 *cloudwatch.DescribeAlarmsInput, _a1 func(*cloudwatch.DescribeAlarmsOutput, bool) bool) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(*cloudwatch.DescribeAlarmsInput, func(*cloudwatch.DescribeAlarmsOutput, bool) bool) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DescribeAlarmsPagesWithContext provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *CloudWatchAPI) DescribeAlarmsPagesWithContext(_a0 context.Context, _a1 *cloudwatch.DescribeAlarmsInput, _a2 func(*cloudwatch.DescribeAlarmsOutput, bool) bool, _a3 ...request.Option) error {
	_va := make([]interface{}, len(_a3))
	for _i := range _a3 {
		_va[_i] = _a3[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _a0, _a1, _a2)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *cloudwatch.DescribeAlarmsInput, func(*cloudwatch.DescribeAlarmsOutput, bool) bool, ...request.Option) error); ok {
		r0 = rf(_a0, _a1, _a2, _a3...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DescribeAlarmsRequest provides a mock function with given fields: _a0
func (_m *CloudWatchAPI) DescribeAlarmsRequest(_a0 *cloudwatch.DescribeAlarmsInput) (*request.Request, *cloudwatch.DescribeAlarmsOutput) {
	ret := _m.Called(_a0)

	var r0 *request.Request
	if rf, ok := ret.Get(0).(func(*cloudwatch.DescribeAlarmsInput) *request.Request); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*request.Request)
		}
	}

	var r1 *cloudwatch.DescribeAlarmsOutput
	if rf, ok := ret.Get(1).(func(*cloudwatch.DescribeAlarmsInput) *cloudwatch.DescribeAlarmsOutput); ok {
		r1 = rf(_a0)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*cloudwatch.DescribeAlarmsOutput)
		}
	}

	return r0, r1
}

// DescribeAlarmsWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *CloudWatchAPI) DescribeAlarmsWithContext(_a0 context.Context, _a1 *cloudwatch.DescribeAlarmsInput, _a2 ...request.Option) (*cloudwatch.DescribeAlarmsOutput, error) {
	_va := make([]interface{}, len(_a2))
	for _i := range _a2 {
		_va[_i] = _a2[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _a0, _a1)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *cloudwatch.DescribeAlarmsOutput
	if rf, ok := ret.Get(0).(func(context.Context, *cloudwatch.DescribeAlarmsInput, ...request.Option) *cloudwatch.DescribeAlarmsOutput); ok {
		r0 = rf(_a0, _a1, _a2...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cloudwatch.DescribeAlarmsOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *cloudwatch.DescribeAlarmsInput, ...request.Option) error); ok {
		r1 = rf(_a0, _a1, _a2...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DescribeAnomalyDetectors provides a mock function with given fields: _a0
func (_m *CloudWatchAPI) DescribeAnomalyDetectors(_a0 *cloudwatch.DescribeAnomalyDetectorsInput) (*cloudwatch.DescribeAnomalyDetectorsOutput, error) {
	ret := _m.Called(_a0)

	var r0 *cloudwatch.DescribeAnomalyDetectorsOutput
	if rf, ok := ret.Get(0).(func(*cloudwatch.DescribeAnomalyDetectorsInput) *cloudwatch.DescribeAnomalyDetectorsOutput); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cloudwatch.DescribeAnomalyDetectorsOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*cloudwatch.DescribeAnomalyDetectorsInput) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DescribeAnomalyDetectorsRequest provides a mock function with given fields: _a0
func (_m *CloudWatchAPI) DescribeAnomalyDetectorsRequest(_a0 *cloudwatch.DescribeAnomalyDetectorsInput) (*request.Request, *cloudwatch.DescribeAnomalyDetectorsOutput) {
	ret := _m.Called(_a0)

	var r0 *request.Request
	if rf, ok := ret.Get(0).(func(*cloudwatch.DescribeAnomalyDetectorsInput) *request.Request); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*request.Request)
		}
	}

	var r1 *cloudwatch.DescribeAnomalyDetectorsOutput
	if rf, ok := ret.Get(1).(func(*cloudwatch.DescribeAnomalyDetectorsInput) *cloudwatch.DescribeAnomalyDetectorsOutput); ok {
		r1 = rf(_a0)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*cloudwatch.DescribeAnomalyDetectorsOutput)
		}
	}

	return r0, r1
}

// DescribeAnomalyDetectorsWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *CloudWatchAPI) DescribeAnomalyDetectorsWithContext(_a0 context.Context, _a1 *cloudwatch.DescribeAnomalyDetectorsInput, _a2 ...request.Option) (*cloudwatch.DescribeAnomalyDetectorsOutput, error) {
	_va := make([]interface{}, len(_a2))
	for _i := range _a2 {
		_va[_i] = _a2[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _a0, _a1)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *cloudwatch.DescribeAnomalyDetectorsOutput
	if rf, ok := ret.Get(0).(func(context.Context, *cloudwatch.DescribeAnomalyDetectorsInput, ...request.Option) *cloudwatch.DescribeAnomalyDetectorsOutput); ok {
		r0 = rf(_a0, _a1, _a2...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cloudwatch.DescribeAnomalyDetectorsOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *cloudwatch.DescribeAnomalyDetectorsInput, ...request.Option) error); ok {
		r1 = rf(_a0, _a1, _a2...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DisableAlarmActions provides a mock function with given fields: _a0
func (_m *CloudWatchAPI) DisableAlarmActions(_a0 *cloudwatch.DisableAlarmActionsInput) (*cloudwatch.DisableAlarmActionsOutput, error) {
	ret := _m.Called(_a0)

	var r0 *cloudwatch.DisableAlarmActionsOutput
	if rf, ok := ret.Get(0).(func(*cloudwatch.DisableAlarmActionsInput) *cloudwatch.DisableAlarmActionsOutput); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cloudwatch.DisableAlarmActionsOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*cloudwatch.DisableAlarmActionsInput) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DisableAlarmActionsRequest provides a mock function with given fields: _a0
func (_m *CloudWatchAPI) DisableAlarmActionsRequest(_a0 *cloudwatch.DisableAlarmActionsInput) (*request.Request, *cloudwatch.DisableAlarmActionsOutput) {
	ret := _m.Called(_a0)

	var r0 *request.Request
	if rf, ok := ret.Get(0).(func(*cloudwatch.DisableAlarmActionsInput) *request.Request); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*request.Request)
		}
	}

	var r1 *cloudwatch.DisableAlarmActionsOutput
	if rf, ok := ret.Get(1).(func(*cloudwatch.DisableAlarmActionsInput) *cloudwatch.DisableAlarmActionsOutput); ok {
		r1 = rf(_a0)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*cloudwatch.DisableAlarmActionsOutput)
		}
	}

	return r0, r1
}

// DisableAlarmActionsWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *CloudWatchAPI) DisableAlarmActionsWithContext(_a0 context.Context, _a1 *cloudwatch.DisableAlarmActionsInput, _a2 ...request.Option) (*cloudwatch.DisableAlarmActionsOutput, error) {
	_va := make([]interface{}, len(_a2))
	for _i := range _a2 {
		_va[_i] = _a2[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _a0, _a1)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *cloudwatch.DisableAlarmActionsOutput
	if rf, ok := ret.Get(0).(func(context.Context, *cloudwatch.DisableAlarmActionsInput, ...request.Option) *cloudwatch.DisableAlarmActionsOutput); ok {
		r0 = rf(_a0, _a1, _a2...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cloudwatch.DisableAlarmActionsOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *cloudwatch.DisableAlarmActionsInput, ...request.Option) error); ok {
		r1 = rf(_a0, _a1, _a2...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EnableAlarmActions provides a mock function with given fields: _a0
func (_m *CloudWatchAPI) EnableAlarmActions(_a0 *cloudwatch.EnableAlarmActionsInput) (*cloudwatch.EnableAlarmActionsOutput, error) {
	ret := _m.Called(_a0)

	var r0 *cloudwatch.EnableAlarmActionsOutput
	if rf, ok := ret.Get(0).(func(*cloudwatch.EnableAlarmActionsInput) *cloudwatch.EnableAlarmActionsOutput); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cloudwatch.EnableAlarmActionsOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*cloudwatch.EnableAlarmActionsInput) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EnableAlarmActionsRequest provides a mock function with given fields: _a0
func (_m *CloudWatchAPI) EnableAlarmActionsRequest(_a0 *cloudwatch.EnableAlarmActionsInput) (*request.Request, *cloudwatch.EnableAlarmActionsOutput) {
	ret := _m.Called(_a0)

	var r0 *request.Request
	if rf, ok := ret.Get(0).(func(*cloudwatch.EnableAlarmActionsInput) *request.Request); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*request.Request)
		}
	}

	var r1 *cloudwatch.EnableAlarmActionsOutput
	if rf, ok := ret.Get(1).(func(*cloudwatch.EnableAlarmActionsInput) *cloudwatch.EnableAlarmActionsOutput); ok {
		r1 = rf(_a0)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*cloudwatch.EnableAlarmActionsOutput)
		}
	}

	return r0, r1
}

// EnableAlarmActionsWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *CloudWatchAPI) EnableAlarmActionsWithContext(_a0 context.Context, _a1 *cloudwatch.EnableAlarmActionsInput, _a2 ...request.Option) (*cloudwatch.EnableAlarmActionsOutput, error) {
	_va := make([]interface{}, len(_a2))
	for _i := range _a2 {
		_va[_i] = _a2[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _a0, _a1)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *cloudwatch.EnableAlarmActionsOutput
	if rf, ok := ret.Get(0).(func(context.Context, *cloudwatch.EnableAlarmActionsInput, ...request.Option) *cloudwatch.EnableAlarmActionsOutput); ok {
		r0 = rf(_a0, _a1, _a2...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cloudwatch.EnableAlarmActionsOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *cloudwatch.EnableAlarmActionsInput, ...request.Option) error); ok {
		r1 = rf(_a0, _a1, _a2...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDashboard provides a mock function with given fields: _a0
func (_m *CloudWatchAPI) GetDashboard(_a0 *cloudwatch.GetDashboardInput) (*cloudwatch.GetDashboardOutput, error) {
	ret := _m.Called(_a0)

	var r0 *cloudwatch.GetDashboardOutput
	if rf, ok := ret.Get(0).(func(*cloudwatch.GetDashboardInput) *cloudwatch.GetDashboardOutput); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cloudwatch.GetDashboardOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*cloudwatch.GetDashboardInput) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDashboardRequest provides a mock function with given fields: _a0
func (_m *CloudWatchAPI) GetDashboardRequest(_a0 *cloudwatch.GetDashboardInput) (*request.Request, *cloudwatch.GetDashboardOutput) {
	ret := _m.Called(_a0)

	var r0 *request.Request
	if rf, ok := ret.Get(0).(func(*cloudwatch.GetDashboardInput) *request.Request); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*request.Request)
		}
	}

	var r1 *cloudwatch.GetDashboardOutput
	if rf, ok := ret.Get(1).(func(*cloudwatch.GetDashboardInput) *cloudwatch.GetDashboardOutput); ok {
		r1 = rf(_a0)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*cloudwatch.GetDashboardOutput)
		}
	}

	return r0, r1
}

// GetDashboardWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *CloudWatchAPI) GetDashboardWithContext(_a0 context.Context, _a1 *cloudwatch.GetDashboardInput, _a2 ...request.Option) (*cloudwatch.GetDashboardOutput, error) {
	_va := make([]interface{}, len(_a2))
	for _i := range _a2 {
		_va[_i] = _a2[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _a0, _a1)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *cloudwatch.GetDashboardOutput
	if rf, ok := ret.Get(0).(func(context.Context, *cloudwatch.GetDashboardInput, ...request.Option) *cloudwatch.GetDashboardOutput); ok {
		r0 = rf(_a0, _a1, _a2...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cloudwatch.GetDashboardOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *cloudwatch.GetDashboardInput, ...request.Option) error); ok {
		r1 = rf(_a0, _a1, _a2...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMetricData provides a mock function with given fields: _a0
func (_m *CloudWatchAPI) GetMetricData(_a0 *cloudwatch.GetMetricDataInput) (*cloudwatch.GetMetricDataOutput, error) {
	ret := _m.Called(_a0)

	var r0 *cloudwatch.GetMetricDataOutput
	if rf, ok := ret.Get(0).(func(*cloudwatch.GetMetricDataInput) *cloudwatch.GetMetricDataOutput); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cloudwatch.GetMetricDataOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*cloudwatch.GetMetricDataInput) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMetricDataPages provides a mock function with given fields: _a0, _a1
func (_m *CloudWatchAPI) GetMetricDataPages(_a0 *cloudwatch.GetMetricDataInput, _a1 func(*cloudwatch.GetMetricDataOutput, bool) bool) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(*cloudwatch.GetMetricDataInput, func(*cloudwatch.GetMetricDataOutput, bool) bool) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetMetricDataPagesWithContext provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *CloudWatchAPI) GetMetricDataPagesWithContext(_a0 context.Context, _a1 *cloudwatch.GetMetricDataInput, _a2 func(*cloudwatch.GetMetricDataOutput, bool) bool, _a3 ...request.Option) error {
	_va := make([]interface{}, len(_a3))
	for _i := range _a3 {
		_va[_i] = _a3[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _a0, _a1, _a2)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *cloudwatch.GetMetricDataInput, func(*cloudwatch.GetMetricDataOutput, bool) bool, ...request.Option) error); ok {
		r0 = rf(_a0, _a1, _a2, _a3...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetMetricDataRequest provides a mock function with given fields: _a0
func (_m *CloudWatchAPI) GetMetricDataRequest(_a0 *cloudwatch.GetMetricDataInput) (*request.Request, *cloudwatch.GetMetricDataOutput) {
	ret := _m.Called(_a0)

	var r0 *request.Request
	if rf, ok := ret.Get(0).(func(*cloudwatch.GetMetricDataInput) *request.Request); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*request.Request)
		}
	}

	var r1 *cloudwatch.GetMetricDataOutput
	if rf, ok := ret.Get(1).(func(*cloudwatch.GetMetricDataInput) *cloudwatch.GetMetricDataOutput); ok {
		r1 = rf(_a0)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*cloudwatch.GetMetricDataOutput)
		}
	}

	return r0, r1
}

// GetMetricDataWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *CloudWatchAPI) GetMetricDataWithContext(_a0 context.Context, _a1 *cloudwatch.GetMetricDataInput, _a2 ...request.Option) (*cloudwatch.GetMetricDataOutput, error) {
	_va := make([]interface{}, len(_a2))
	for _i := range _a2 {
		_va[_i] = _a2[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _a0, _a1)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *cloudwatch.GetMetricDataOutput
	if rf, ok := ret.Get(0).(func(context.Context, *cloudwatch.GetMetricDataInput, ...request.Option) *cloudwatch.GetMetricDataOutput); ok {
		r0 = rf(_a0, _a1, _a2...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cloudwatch.GetMetricDataOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *cloudwatch.GetMetricDataInput, ...request.Option) error); ok {
		r1 = rf(_a0, _a1, _a2...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMetricStatistics provides a mock function with given fields: _a0
func (_m *CloudWatchAPI) GetMetricStatistics(_a0 *cloudwatch.GetMetricStatisticsInput) (*cloudwatch.GetMetricStatisticsOutput, error) {
	ret := _m.Called(_a0)

	var r0 *cloudwatch.GetMetricStatisticsOutput
	if rf, ok := ret.Get(0).(func(*cloudwatch.GetMetricStatisticsInput) *cloudwatch.GetMetricStatisticsOutput); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cloudwatch.GetMetricStatisticsOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*cloudwatch.GetMetricStatisticsInput) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMetricStatisticsRequest provides a mock function with given fields: _a0
func (_m *CloudWatchAPI) GetMetricStatisticsRequest(_a0 *cloudwatch.GetMetricStatisticsInput) (*request.Request, *cloudwatch.GetMetricStatisticsOutput) {
	ret := _m.Called(_a0)

	var r0 *request.Request
	if rf, ok := ret.Get(0).(func(*cloudwatch.GetMetricStatisticsInput) *request.Request); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*request.Request)
		}
	}

	var r1 *cloudwatch.GetMetricStatisticsOutput
	if rf, ok := ret.Get(1).(func(*cloudwatch.GetMetricStatisticsInput) *cloudwatch.GetMetricStatisticsOutput); ok {
		r1 = rf(_a0)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*cloudwatch.GetMetricStatisticsOutput)
		}
	}

	return r0, r1
}

// GetMetricStatisticsWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *CloudWatchAPI) GetMetricStatisticsWithContext(_a0 context.Context, _a1 *cloudwatch.GetMetricStatisticsInput, _a2 ...request.Option) (*cloudwatch.GetMetricStatisticsOutput, error) {
	_va := make([]interface{}, len(_a2))
	for _i := range _a2 {
		_va[_i] = _a2[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _a0, _a1)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *cloudwatch.GetMetricStatisticsOutput
	if rf, ok := ret.Get(0).(func(context.Context, *cloudwatch.GetMetricStatisticsInput, ...request.Option) *cloudwatch.GetMetricStatisticsOutput); ok {
		r0 = rf(_a0, _a1, _a2...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cloudwatch.GetMetricStatisticsOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *cloudwatch.GetMetricStatisticsInput, ...request.Option) error); ok {
		r1 = rf(_a0, _a1, _a2...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMetricWidgetImage provides a mock function with given fields: _a0
func (_m *CloudWatchAPI) GetMetricWidgetImage(_a0 *cloudwatch.GetMetricWidgetImageInput) (*cloudwatch.GetMetricWidgetImageOutput, error) {
	ret := _m.Called(_a0)

	var r0 *cloudwatch.GetMetricWidgetImageOutput
	if rf, ok := ret.Get(0).(func(*cloudwatch.GetMetricWidgetImageInput) *cloudwatch.GetMetricWidgetImageOutput); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cloudwatch.GetMetricWidgetImageOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*cloudwatch.GetMetricWidgetImageInput) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMetricWidgetImageRequest provides a mock function with given fields: _a0
func (_m *CloudWatchAPI) GetMetricWidgetImageRequest(_a0 *cloudwatch.GetMetricWidgetImageInput) (*request.Request, *cloudwatch.GetMetricWidgetImageOutput) {
	ret := _m.Called(_a0)

	var r0 *request.Request
	if rf, ok := ret.Get(0).(func(*cloudwatch.GetMetricWidgetImageInput) *request.Request); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*request.Request)
		}
	}

	var r1 *cloudwatch.GetMetricWidgetImageOutput
	if rf, ok := ret.Get(1).(func(*cloudwatch.GetMetricWidgetImageInput) *cloudwatch.GetMetricWidgetImageOutput); ok {
		r1 = rf(_a0)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*cloudwatch.GetMetricWidgetImageOutput)
		}
	}

	return r0, r1
}

// GetMetricWidgetImageWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *CloudWatchAPI) GetMetricWidgetImageWithContext(_a0 context.Context, _a1 *cloudwatch.GetMetricWidgetImageInput, _a2 ...request.Option) (*cloudwatch.GetMetricWidgetImageOutput, error) {
	_va := make([]interface{}, len(_a2))
	for _i := range _a2 {
		_va[_i] = _a2[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _a0, _a1)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *cloudwatch.GetMetricWidgetImageOutput
	if rf, ok := ret.Get(0).(func(context.Context, *cloudwatch.GetMetricWidgetImageInput, ...request.Option) *cloudwatch.GetMetricWidgetImageOutput); ok {
		r0 = rf(_a0, _a1, _a2...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cloudwatch.GetMetricWidgetImageOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *cloudwatch.GetMetricWidgetImageInput, ...request.Option) error); ok {
		r1 = rf(_a0, _a1, _a2...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListDashboards provides a mock function with given fields: _a0
func (_m *CloudWatchAPI) ListDashboards(_a0 *cloudwatch.ListDashboardsInput) (*cloudwatch.ListDashboardsOutput, error) {
	ret := _m.Called(_a0)

	var r0 *cloudwatch.ListDashboardsOutput
	if rf, ok := ret.Get(0).(func(*cloudwatch.ListDashboardsInput) *cloudwatch.ListDashboardsOutput); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cloudwatch.ListDashboardsOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*cloudwatch.ListDashboardsInput) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListDashboardsPages provides a mock function with given fields: _a0, _a1
func (_m *CloudWatchAPI) ListDashboardsPages(_a0 *cloudwatch.ListDashboardsInput, _a1 func(*cloudwatch.ListDashboardsOutput, bool) bool) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(*cloudwatch.ListDashboardsInput, func(*cloudwatch.ListDashboardsOutput, bool) bool) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ListDashboardsPagesWithContext provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *CloudWatchAPI) ListDashboardsPagesWithContext(_a0 context.Context, _a1 *cloudwatch.ListDashboardsInput, _a2 func(*cloudwatch.ListDashboardsOutput, bool) bool, _a3 ...request.Option) error {
	_va := make([]interface{}, len(_a3))
	for _i := range _a3 {
		_va[_i] = _a3[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _a0, _a1, _a2)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *cloudwatch.ListDashboardsInput, func(*cloudwatch.ListDashboardsOutput, bool) bool, ...request.Option) error); ok {
		r0 = rf(_a0, _a1, _a2, _a3...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ListDashboardsRequest provides a mock function with given fields: _a0
func (_m *CloudWatchAPI) ListDashboardsRequest(_a0 *cloudwatch.ListDashboardsInput) (*request.Request, *cloudwatch.ListDashboardsOutput) {
	ret := _m.Called(_a0)

	var r0 *request.Request
	if rf, ok := ret.Get(0).(func(*cloudwatch.ListDashboardsInput) *request.Request); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*request.Request)
		}
	}

	var r1 *cloudwatch.ListDashboardsOutput
	if rf, ok := ret.Get(1).(func(*cloudwatch.ListDashboardsInput) *cloudwatch.ListDashboardsOutput); ok {
		r1 = rf(_a0)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*cloudwatch.ListDashboardsOutput)
		}
	}

	return r0, r1
}

// ListDashboardsWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *CloudWatchAPI) ListDashboardsWithContext(_a0 context.Context, _a1 *cloudwatch.ListDashboardsInput, _a2 ...request.Option) (*cloudwatch.ListDashboardsOutput, error) {
	_va := make([]interface{}, len(_a2))
	for _i := range _a2 {
		_va[_i] = _a2[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _a0, _a1)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *cloudwatch.ListDashboardsOutput
	if rf, ok := ret.Get(0).(func(context.Context, *cloudwatch.ListDashboardsInput, ...request.Option) *cloudwatch.ListDashboardsOutput); ok {
		r0 = rf(_a0, _a1, _a2...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cloudwatch.ListDashboardsOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *cloudwatch.ListDashboardsInput, ...request.Option) error); ok {
		r1 = rf(_a0, _a1, _a2...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListMetrics provides a mock function with given fields: _a0
func (_m *CloudWatchAPI) ListMetrics(_a0 *cloudwatch.ListMetricsInput) (*cloudwatch.ListMetricsOutput, error) {
	ret := _m.Called(_a0)

	var r0 *cloudwatch.ListMetricsOutput
	if rf, ok := ret.Get(0).(func(*cloudwatch.ListMetricsInput) *cloudwatch.ListMetricsOutput); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cloudwatch.ListMetricsOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*cloudwatch.ListMetricsInput) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListMetricsPages provides a mock function with given fields: _a0, _a1
func (_m *CloudWatchAPI) ListMetricsPages(_a0 *cloudwatch.ListMetricsInput, _a1 func(*cloudwatch.ListMetricsOutput, bool) bool) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(*cloudwatch.ListMetricsInput, func(*cloudwatch.ListMetricsOutput, bool) bool) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ListMetricsPagesWithContext provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *CloudWatchAPI) ListMetricsPagesWithContext(_a0 context.Context, _a1 *cloudwatch.ListMetricsInput, _a2 func(*cloudwatch.ListMetricsOutput, bool) bool, _a3 ...request.Option) error {
	_va := make([]interface{}, len(_a3))
	for _i := range _a3 {
		_va[_i] = _a3[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _a0, _a1, _a2)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *cloudwatch.ListMetricsInput, func(*cloudwatch.ListMetricsOutput, bool) bool, ...request.Option) error); ok {
		r0 = rf(_a0, _a1, _a2, _a3...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ListMetricsRequest provides a mock function with given fields: _a0
func (_m *CloudWatchAPI) ListMetricsRequest(_a0 *cloudwatch.ListMetricsInput) (*request.Request, *cloudwatch.ListMetricsOutput) {
	ret := _m.Called(_a0)

	var r0 *request.Request
	if rf, ok := ret.Get(0).(func(*cloudwatch.ListMetricsInput) *request.Request); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*request.Request)
		}
	}

	var r1 *cloudwatch.ListMetricsOutput
	if rf, ok := ret.Get(1).(func(*cloudwatch.ListMetricsInput) *cloudwatch.ListMetricsOutput); ok {
		r1 = rf(_a0)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*cloudwatch.ListMetricsOutput)
		}
	}

	return r0, r1
}

// ListMetricsWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *CloudWatchAPI) ListMetricsWithContext(_a0 context.Context, _a1 *cloudwatch.ListMetricsInput, _a2 ...request.Option) (*cloudwatch.ListMetricsOutput, error) {
	_va := make([]interface{}, len(_a2))
	for _i := range _a2 {
		_va[_i] = _a2[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _a0, _a1)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *cloudwatch.ListMetricsOutput
	if rf, ok := ret.Get(0).(func(context.Context, *cloudwatch.ListMetricsInput, ...request.Option) *cloudwatch.ListMetricsOutput); ok {
		r0 = rf(_a0, _a1, _a2...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cloudwatch.ListMetricsOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *cloudwatch.ListMetricsInput, ...request.Option) error); ok {
		r1 = rf(_a0, _a1, _a2...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListTagsForResource provides a mock function with given fields: _a0
func (_m *CloudWatchAPI) ListTagsForResource(_a0 *cloudwatch.ListTagsForResourceInput) (*cloudwatch.ListTagsForResourceOutput, error) {
	ret := _m.Called(_a0)

	var r0 *cloudwatch.ListTagsForResourceOutput
	if rf, ok := ret.Get(0).(func(*cloudwatch.ListTagsForResourceInput) *cloudwatch.ListTagsForResourceOutput); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cloudwatch.ListTagsForResourceOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*cloudwatch.ListTagsForResourceInput) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListTagsForResourceRequest provides a mock function with given fields: _a0
func (_m *CloudWatchAPI) ListTagsForResourceRequest(_a0 *cloudwatch.ListTagsForResourceInput) (*request.Request, *cloudwatch.ListTagsForResourceOutput) {
	ret := _m.Called(_a0)

	var r0 *request.Request
	if rf, ok := ret.Get(0).(func(*cloudwatch.ListTagsForResourceInput) *request.Request); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*request.Request)
		}
	}

	var r1 *cloudwatch.ListTagsForResourceOutput
	if rf, ok := ret.Get(1).(func(*cloudwatch.ListTagsForResourceInput) *cloudwatch.ListTagsForResourceOutput); ok {
		r1 = rf(_a0)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*cloudwatch.ListTagsForResourceOutput)
		}
	}

	return r0, r1
}

// ListTagsForResourceWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *CloudWatchAPI) ListTagsForResourceWithContext(_a0 context.Context, _a1 *cloudwatch.ListTagsForResourceInput, _a2 ...request.Option) (*cloudwatch.ListTagsForResourceOutput, error) {
	_va := make([]interface{}, len(_a2))
	for _i := range _a2 {
		_va[_i] = _a2[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _a0, _a1)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *cloudwatch.ListTagsForResourceOutput
	if rf, ok := ret.Get(0).(func(context.Context, *cloudwatch.ListTagsForResourceInput, ...request.Option) *cloudwatch.ListTagsForResourceOutput); ok {
		r0 = rf(_a0, _a1, _a2...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cloudwatch.ListTagsForResourceOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *cloudwatch.ListTagsForResourceInput, ...request.Option) error); ok {
		r1 = rf(_a0, _a1, _a2...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PutAnomalyDetector provides a mock function with given fields: _a0
func (_m *CloudWatchAPI) PutAnomalyDetector(_a0 *cloudwatch.PutAnomalyDetectorInput) (*cloudwatch.PutAnomalyDetectorOutput, error) {
	ret := _m.Called(_a0)

	var r0 *cloudwatch.PutAnomalyDetectorOutput
	if rf, ok := ret.Get(0).(func(*cloudwatch.PutAnomalyDetectorInput) *cloudwatch.PutAnomalyDetectorOutput); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cloudwatch.PutAnomalyDetectorOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*cloudwatch.PutAnomalyDetectorInput) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PutAnomalyDetectorRequest provides a mock function with given fields: _a0
func (_m *CloudWatchAPI) PutAnomalyDetectorRequest(_a0 *cloudwatch.PutAnomalyDetectorInput) (*request.Request, *cloudwatch.PutAnomalyDetectorOutput) {
	ret := _m.Called(_a0)

	var r0 *request.Request
	if rf, ok := ret.Get(0).(func(*cloudwatch.PutAnomalyDetectorInput) *request.Request); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*request.Request)
		}
	}

	var r1 *cloudwatch.PutAnomalyDetectorOutput
	if rf, ok := ret.Get(1).(func(*cloudwatch.PutAnomalyDetectorInput) *cloudwatch.PutAnomalyDetectorOutput); ok {
		r1 = rf(_a0)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*cloudwatch.PutAnomalyDetectorOutput)
		}
	}

	return r0, r1
}

// PutAnomalyDetectorWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *CloudWatchAPI) PutAnomalyDetectorWithContext(_a0 context.Context, _a1 *cloudwatch.PutAnomalyDetectorInput, _a2 ...request.Option) (*cloudwatch.PutAnomalyDetectorOutput, error) {
	_va := make([]interface{}, len(_a2))
	for _i := range _a2 {
		_va[_i] = _a2[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _a0, _a1)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *cloudwatch.PutAnomalyDetectorOutput
	if rf, ok := ret.Get(0).(func(context.Context, *cloudwatch.PutAnomalyDetectorInput, ...request.Option) *cloudwatch.PutAnomalyDetectorOutput); ok {
		r0 = rf(_a0, _a1, _a2...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cloudwatch.PutAnomalyDetectorOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *cloudwatch.PutAnomalyDetectorInput, ...request.Option) error); ok {
		r1 = rf(_a0, _a1, _a2...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PutDashboard provides a mock function with given fields: _a0
func (_m *CloudWatchAPI) PutDashboard(_a0 *cloudwatch.PutDashboardInput) (*cloudwatch.PutDashboardOutput, error) {
	ret := _m.Called(_a0)

	var r0 *cloudwatch.PutDashboardOutput
	if rf, ok := ret.Get(0).(func(*cloudwatch.PutDashboardInput) *cloudwatch.PutDashboardOutput); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cloudwatch.PutDashboardOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*cloudwatch.PutDashboardInput) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PutDashboardRequest provides a mock function with given fields: _a0
func (_m *CloudWatchAPI) PutDashboardRequest(_a0 *cloudwatch.PutDashboardInput) (*request.Request, *cloudwatch.PutDashboardOutput) {
	ret := _m.Called(_a0)

	var r0 *request.Request
	if rf, ok := ret.Get(0).(func(*cloudwatch.PutDashboardInput) *request.Request); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*request.Request)
		}
	}

	var r1 *cloudwatch.PutDashboardOutput
	if rf, ok := ret.Get(1).(func(*cloudwatch.PutDashboardInput) *cloudwatch.PutDashboardOutput); ok {
		r1 = rf(_a0)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*cloudwatch.PutDashboardOutput)
		}
	}

	return r0, r1
}

// PutDashboardWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *CloudWatchAPI) PutDashboardWithContext(_a0 context.Context, _a1 *cloudwatch.PutDashboardInput, _a2 ...request.Option) (*cloudwatch.PutDashboardOutput, error) {
	_va := make([]interface{}, len(_a2))
	for _i := range _a2 {
		_va[_i] = _a2[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _a0, _a1)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *cloudwatch.PutDashboardOutput
	if rf, ok := ret.Get(0).(func(context.Context, *cloudwatch.PutDashboardInput, ...request.Option) *cloudwatch.PutDashboardOutput); ok {
		r0 = rf(_a0, _a1, _a2...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cloudwatch.PutDashboardOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *cloudwatch.PutDashboardInput, ...request.Option) error); ok {
		r1 = rf(_a0, _a1, _a2...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PutMetricAlarm provides a mock function with given fields: _a0
func (_m *CloudWatchAPI) PutMetricAlarm(_a0 *cloudwatch.PutMetricAlarmInput) (*cloudwatch.PutMetricAlarmOutput, error) {
	ret := _m.Called(_a0)

	var r0 *cloudwatch.PutMetricAlarmOutput
	if rf, ok := ret.Get(0).(func(*cloudwatch.PutMetricAlarmInput) *cloudwatch.PutMetricAlarmOutput); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cloudwatch.PutMetricAlarmOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*cloudwatch.PutMetricAlarmInput) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PutMetricAlarmRequest provides a mock function with given fields: _a0
func (_m *CloudWatchAPI) PutMetricAlarmRequest(_a0 *cloudwatch.PutMetricAlarmInput) (*request.Request, *cloudwatch.PutMetricAlarmOutput) {
	ret := _m.Called(_a0)

	var r0 *request.Request
	if rf, ok := ret.Get(0).(func(*cloudwatch.PutMetricAlarmInput) *request.Request); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*request.Request)
		}
	}

	var r1 *cloudwatch.PutMetricAlarmOutput
	if rf, ok := ret.Get(1).(func(*cloudwatch.PutMetricAlarmInput) *cloudwatch.PutMetricAlarmOutput); ok {
		r1 = rf(_a0)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*cloudwatch.PutMetricAlarmOutput)
		}
	}

	return r0, r1
}

// PutMetricAlarmWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *CloudWatchAPI) PutMetricAlarmWithContext(_a0 context.Context, _a1 *cloudwatch.PutMetricAlarmInput, _a2 ...request.Option) (*cloudwatch.PutMetricAlarmOutput, error) {
	_va := make([]interface{}, len(_a2))
	for _i := range _a2 {
		_va[_i] = _a2[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _a0, _a1)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *cloudwatch.PutMetricAlarmOutput
	if rf, ok := ret.Get(0).(func(context.Context, *cloudwatch.PutMetricAlarmInput, ...request.Option) *cloudwatch.PutMetricAlarmOutput); ok {
		r0 = rf(_a0, _a1, _a2...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cloudwatch.PutMetricAlarmOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *cloudwatch.PutMetricAlarmInput, ...request.Option) error); ok {
		r1 = rf(_a0, _a1, _a2...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PutMetricData provides a mock function with given fields: _a0
func (_m *CloudWatchAPI) PutMetricData(_a0 *cloudwatch.PutMetricDataInput) (*cloudwatch.PutMetricDataOutput, error) {
	ret := _m.Called(_a0)

	var r0 *cloudwatch.PutMetricDataOutput
	if rf, ok := ret.Get(0).(func(*cloudwatch.PutMetricDataInput) *cloudwatch.PutMetricDataOutput); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cloudwatch.PutMetricDataOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*cloudwatch.PutMetricDataInput) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PutMetricDataRequest provides a mock function with given fields: _a0
func (_m *CloudWatchAPI) PutMetricDataRequest(_a0 *cloudwatch.PutMetricDataInput) (*request.Request, *cloudwatch.PutMetricDataOutput) {
	ret := _m.Called(_a0)

	var r0 *request.Request
	if rf, ok := ret.Get(0).(func(*cloudwatch.PutMetricDataInput) *request.Request); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*request.Request)
		}
	}

	var r1 *cloudwatch.PutMetricDataOutput
	if rf, ok := ret.Get(1).(func(*cloudwatch.PutMetricDataInput) *cloudwatch.PutMetricDataOutput); ok {
		r1 = rf(_a0)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*cloudwatch.PutMetricDataOutput)
		}
	}

	return r0, r1
}

// PutMetricDataWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *CloudWatchAPI) PutMetricDataWithContext(_a0 context.Context, _a1 *cloudwatch.PutMetricDataInput, _a2 ...request.Option) (*cloudwatch.PutMetricDataOutput, error) {
	_va := make([]interface{}, len(_a2))
	for _i := range _a2 {
		_va[_i] = _a2[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _a0, _a1)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *cloudwatch.PutMetricDataOutput
	if rf, ok := ret.Get(0).(func(context.Context, *cloudwatch.PutMetricDataInput, ...request.Option) *cloudwatch.PutMetricDataOutput); ok {
		r0 = rf(_a0, _a1, _a2...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cloudwatch.PutMetricDataOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *cloudwatch.PutMetricDataInput, ...request.Option) error); ok {
		r1 = rf(_a0, _a1, _a2...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetAlarmState provides a mock function with given fields: _a0
func (_m *CloudWatchAPI) SetAlarmState(_a0 *cloudwatch.SetAlarmStateInput) (*cloudwatch.SetAlarmStateOutput, error) {
	ret := _m.Called(_a0)

	var r0 *cloudwatch.SetAlarmStateOutput
	if rf, ok := ret.Get(0).(func(*cloudwatch.SetAlarmStateInput) *cloudwatch.SetAlarmStateOutput); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cloudwatch.SetAlarmStateOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*cloudwatch.SetAlarmStateInput) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetAlarmStateRequest provides a mock function with given fields: _a0
func (_m *CloudWatchAPI) SetAlarmStateRequest(_a0 *cloudwatch.SetAlarmStateInput) (*request.Request, *cloudwatch.SetAlarmStateOutput) {
	ret := _m.Called(_a0)

	var r0 *request.Request
	if rf, ok := ret.Get(0).(func(*cloudwatch.SetAlarmStateInput) *request.Request); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*request.Request)
		}
	}

	var r1 *cloudwatch.SetAlarmStateOutput
	if rf, ok := ret.Get(1).(func(*cloudwatch.SetAlarmStateInput) *cloudwatch.SetAlarmStateOutput); ok {
		r1 = rf(_a0)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*cloudwatch.SetAlarmStateOutput)
		}
	}

	return r0, r1
}

// SetAlarmStateWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *CloudWatchAPI) SetAlarmStateWithContext(_a0 context.Context, _a1 *cloudwatch.SetAlarmStateInput, _a2 ...request.Option) (*cloudwatch.SetAlarmStateOutput, error) {
	_va := make([]interface{}, len(_a2))
	for _i := range _a2 {
		_va[_i] = _a2[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _a0, _a1)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *cloudwatch.SetAlarmStateOutput
	if rf, ok := ret.Get(0).(func(context.Context, *cloudwatch.SetAlarmStateInput, ...request.Option) *cloudwatch.SetAlarmStateOutput); ok {
		r0 = rf(_a0, _a1, _a2...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cloudwatch.SetAlarmStateOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *cloudwatch.SetAlarmStateInput, ...request.Option) error); ok {
		r1 = rf(_a0, _a1, _a2...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TagResource provides a mock function with given fields: _a0
func (_m *CloudWatchAPI) TagResource(_a0 *cloudwatch.TagResourceInput) (*cloudwatch.TagResourceOutput, error) {
	ret := _m.Called(_a0)

	var r0 *cloudwatch.TagResourceOutput
	if rf, ok := ret.Get(0).(func(*cloudwatch.TagResourceInput) *cloudwatch.TagResourceOutput); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cloudwatch.TagResourceOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*cloudwatch.TagResourceInput) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TagResourceRequest provides a mock function with given fields: _a0
func (_m *CloudWatchAPI) TagResourceRequest(_a0 *cloudwatch.TagResourceInput) (*request.Request, *cloudwatch.TagResourceOutput) {
	ret := _m.Called(_a0)

	var r0 *request.Request
	if rf, ok := ret.Get(0).(func(*cloudwatch.TagResourceInput) *request.Request); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*request.Request)
		}
	}

	var r1 *cloudwatch.TagResourceOutput
	if rf, ok := ret.Get(1).(func(*cloudwatch.TagResourceInput) *cloudwatch.TagResourceOutput); ok {
		r1 = rf(_a0)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*cloudwatch.TagResourceOutput)
		}
	}

	return r0, r1
}

// TagResourceWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *CloudWatchAPI) TagResourceWithContext(_a0 context.Context, _a1 *cloudwatch.TagResourceInput, _a2 ...request.Option) (*cloudwatch.TagResourceOutput, error) {
	_va := make([]interface{}, len(_a2))
	for _i := range _a2 {
		_va[_i] = _a2[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _a0, _a1)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *cloudwatch.TagResourceOutput
	if rf, ok := ret.Get(0).(func(context.Context, *cloudwatch.TagResourceInput, ...request.Option) *cloudwatch.TagResourceOutput); ok {
		r0 = rf(_a0, _a1, _a2...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cloudwatch.TagResourceOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *cloudwatch.TagResourceInput, ...request.Option) error); ok {
		r1 = rf(_a0, _a1, _a2...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UntagResource provides a mock function with given fields: _a0
func (_m *CloudWatchAPI) UntagResource(_a0 *cloudwatch.UntagResourceInput) (*cloudwatch.UntagResourceOutput, error) {
	ret := _m.Called(_a0)

	var r0 *cloudwatch.UntagResourceOutput
	if rf, ok := ret.Get(0).(func(*cloudwatch.UntagResourceInput) *cloudwatch.UntagResourceOutput); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cloudwatch.UntagResourceOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*cloudwatch.UntagResourceInput) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UntagResourceRequest provides a mock function with given fields: _a0
func (_m *CloudWatchAPI) UntagResourceRequest(_a0 *cloudwatch.UntagResourceInput) (*request.Request, *cloudwatch.UntagResourceOutput) {
	ret := _m.Called(_a0)

	var r0 *request.Request
	if rf, ok := ret.Get(0).(func(*cloudwatch.UntagResourceInput) *request.Request); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*request.Request)
		}
	}

	var r1 *cloudwatch.UntagResourceOutput
	if rf, ok := ret.Get(1).(func(*cloudwatch.UntagResourceInput) *cloudwatch.UntagResourceOutput); ok {
		r1 = rf(_a0)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*cloudwatch.UntagResourceOutput)
		}
	}

	return r0, r1
}

// UntagResourceWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *CloudWatchAPI) UntagResourceWithContext(_a0 context.Context, _a1 *cloudwatch.UntagResourceInput, _a2 ...request.Option) (*cloudwatch.UntagResourceOutput, error) {
	_va := make([]interface{}, len(_a2))
	for _i := range _a2 {
		_va[_i] = _a2[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _a0, _a1)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *cloudwatch.UntagResourceOutput
	if rf, ok := ret.Get(0).(func(context.Context, *cloudwatch.UntagResourceInput, ...request.Option) *cloudwatch.UntagResourceOutput); ok {
		r0 = rf(_a0, _a1, _a2...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cloudwatch.UntagResourceOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *cloudwatch.UntagResourceInput, ...request.Option) error); ok {
		r1 = rf(_a0, _a1, _a2...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WaitUntilAlarmExists provides a mock function with given fields: _a0
func (_m *CloudWatchAPI) WaitUntilAlarmExists(_a0 *cloudwatch.DescribeAlarmsInput) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*cloudwatch.DescribeAlarmsInput) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WaitUntilAlarmExistsWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *CloudWatchAPI) WaitUntilAlarmExistsWithContext(_a0 context.Context, _a1 *cloudwatch.DescribeAlarmsInput, _a2 ...request.WaiterOption) error {
	_va := make([]interface{}, len(_a2))
	for _i := range _a2 {
		_va[_i] = _a2[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _a0, _a1)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *cloudwatch.DescribeAlarmsInput, ...request.WaiterOption) error); ok {
		r0 = rf(_a0, _a1, _a2...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
