#!/bin/sh

set -e

pkg=$1

find . -name '*.go' | xargs -n 1 sed -i "" -e "s|convox/rack/$1|convox/rack/pkg/$1|g"
git checkout vendor
mv $1 pkg/
go install ./...
git add .
git commit -m "move $1 to pkg"
