#!/bin/bash

set -e

nl=$'\n'

die() { echo $*; exit 1; }

gethub() {
  local path=$1 filter=$2 query=$3
  curl -s -u :$token "https://api.github.com$path?$query" | tr -d '\t\r' | jq -r "$filter"
}

posthub() {
  local path=$1 data=$2 filter=$3
  curl -X POST -s -u :$token -d "$data" "https://api.github.com$path" | tr -d '\t\r' | jq -r "$filter"
}

merge() {
  local pr=$1
  local base=$(git rev-parse --abbrev-ref HEAD)
  local remote="https://github.com/$(gethub /repos/convox/rack/pulls/$1 ".head.repo.full_name")"
  local ref=$(gethub /repos/convox/rack/pulls/$1 ".head.ref")
  local title=$(gethub /repos/convox/rack/pulls/$1 ".title")
  local body=$(gethub /repos/convox/rack/pulls/$1 ".body")
  local work="merge-${ref}"

  local message="[#${1}] ${title}${nl}${nl}${body}"

  git branch -D $work >/dev/null 2>&1 || true
  git fetch $remote $ref:$work
  git checkout $work
  git reset --soft $(git merge-base $work $base)
  git commit -m "$message"
  git rebase $base || (git rebase --abort; git checkout $base; die "could not rebase: $pr")
  git checkout $base
  git merge --no-edit $work
  git branch -d $work
}

pr_body() {
  echo '## Pull Requests'
  gethub /repos/convox/rack/issues "sort_by(.number)|.[]|\"closes #\\(.number) \\(.title) [@\\(.user.login)]\"" "labels=status/6-merge" | while read pr; do
    echo "  - $pr"
  done

  echo

  curl -s https://raw.githubusercontent.com/wiki/convox/rack/Milestone-Release-Checklist.md
}

pr_create() {
  local release_version=$1
  local body=$(pr_body | awk 1 ORS='\\n')
  local data="{\"title\":\"[RELEASE] $release_version\",\"head\":\"$release_version\",\"base\":\"master\",\"body\":\"$body\"}"

  echo "creating pr for release_version: $release_version"
  local num=$(posthub /repos/convox/rack/pulls "$data" ".number")
  echo "https://github.com/convox/rack/pull/$num"
}

pr_update() {
  local pr=$1 release_version=$2
  local body=$(pr_body | awk 1 ORS='\\n')
  local data="{\"body\":\"$body\"}"

  echo "updating pr for release_version: $release_version"
  local num=$(posthub /repos/convox/rack/pulls/$pr "$data" ".number")
  echo "https://github.com/convox/rack/pull/$num"
}

release_version=$1
status=$(git status --porcelain)
token=$(git config github.token)

[ -n "$release_version" ]    || die "must specify release_version as argument (eg 20160715)"
[ -n "$token" ]        || die "no github.token found in git config"
[ -x "$(which curl)" ] || die "needs curl"
[ -x "$(which jq)" ]   || die "needs jq"
[ -z "$status" ]       || die "must have clean git working tree"

git checkout master
git branch -D $release_version >/dev/null 2>&1 || true
git checkout -b $release_version

gethub /repos/convox/rack/issues ".[]|select(.pull_request)|.number" "labels=status/6-merge" | while read pr; do
  echo "merging: $pr"
  merge $pr
done

git push origin $release_version -f

release=$(gethub /repos/convox/rack/pulls ".[]|select(.head.ref==\"$release_version\")|select(.head.repo.full_name==\"convox/rack\").number")

[ -n "$release" ] && pr_update $release $release_version || pr_create $release_version
