package aws_test

import (
	"testing"

	"github.com/convox/rack/api/awsutil"
	"github.com/convox/rack/test"
	"github.com/stretchr/testify/assert"
)

func TestServiceWebhookURL(t *testing.T) {
	provider := StubAwsProvider(
		test.DescribeStackNotFound("convox-mywebhook"),
		test.DescribeStackNotFound("mywebhook"),
		cycleServiceCreateWebhook,
	)
	defer provider.Close()

	params := map[string]string{
		"url": "https://www.example.com",
	}

	url := "http://notifications.example.org/sns?endpoint=https%3A%2F%2Fwww.example.com"
	s, err := provider.ServiceCreate("mywebhook", "webhook", params)

	if assert.Nil(t, err) {
		assert.Equal(t, url, s.Parameters["Url"])
	}
}

var cycleServiceDescribeStacks1 = awsutil.Cycle{
	awsutil.Request{"/", "", `Action=DescribeStacks&StackName=convox-mywebhook&Version=2010-05-15`},
	awsutil.Response{
		400,
		`<DescribeStacksResponse xmlns="http://cloudformation.amazonaws.com/doc/2010-05-15/">
			<DescribeStacksResult>
				<Stacks>
					<member>
						<Outputs>
							<member>
								<OutputKey>CustomTopic</OutputKey>
								<OutputValue>arn:aws:lambda:us-east-1:778743527532:function:convox-CustomTopic-1VJ75T6FBGORL</OutputValue>
							</member>
							<member>
								<OutputKey>Internal</OutputKey>
								<OutputValue>No</OutputValue>
							</member>
							<member>
								<OutputKey>SettingsBucket</OutputKey>
								<OutputValue>convox-settings-c21v4pfz9zpc</OutputValue>
							</member>
							<member>
								<OutputKey>Vpc</OutputKey>
								<OutputValue>vpc-08c5726c</OutputValue>
							</member>
							<member>
								<OutputKey>Dashboard</OutputKey>
								<OutputValue>convox-1423604943.us-east-1.elb.amazonaws.com</OutputValue>
							</member>
							<member>
								<OutputKey>EncryptionKey</OutputKey>
								<OutputValue>arn:aws:kms:us-east-1:778743527532:key/f1752bdd-5805-4891-9208-f16be3a4ccd6</OutputValue>
							</member>
							<member>
								<OutputKey>DockerImageApi</OutputKey>
								<OutputValue>convox/api:20160820033210</OutputValue>
							</member>
							<member>
								<OutputKey>NotificationTopic</OutputKey>
								<OutputValue>arn:aws:sns:us-east-1:778743527532:convox-notifications</OutputValue>
							</member>
							<member>
								<OutputKey>Rack</OutputKey>
								<OutputValue>convox</OutputValue>
							</member>
							<member>
								<OutputKey>Autoscale</OutputKey>
								<OutputValue>false</OutputValue>
							</member>
							<member>
								<OutputKey>AwsRegion</OutputKey>
								<OutputValue>us-east-1</OutputValue>
							</member>
							<member>
								<OutputKey>DynamoBuilds</OutputKey>
								<OutputValue>convox-builds</OutputValue>
							</member>
							<member>
								<OutputKey>Private</OutputKey>
								<OutputValue>No</OutputValue>
							</member>
							<member>
								<OutputKey>Release</OutputKey>
								<OutputValue>20160820033210</OutputValue>
							</member>
							<member>
								<OutputKey>NotificationHost</OutputKey>
								<OutputValue>convox-1423604943.us-east-1.elb.amazonaws.com</OutputValue>
							</member>
							<member>
								<OutputKey>Password</OutputKey>
								<OutputValue>rZPfAaETBaRcmWSYTqulMXcfyXlFlR</OutputValue>
							</member>
							<member>
								<OutputKey>SubnetsPrivate</OutputKey>
								<OutputValue/>
							</member>
							<member>
								<OutputKey>AwsAccess</OutputKey>
								<OutputValue>AKIAIQWYIWCZS6S3K5AA</OutputValue>
							</member>
							<member>
								<OutputKey>Cluster</OutputKey>
								<OutputValue>convox-Cluster-1EQQWK182GWYD</OutputValue>
							</member>
							<member>
								<OutputKey>Provider</OutputKey>
								<OutputValue>aws</OutputValue>
							</member>
							<member>
								<OutputKey>Subnets</OutputKey>
								<OutputValue>subnet-8ea696a5,subnet-95a841e3,subnet-5387870a</OutputValue>
							</member>
							<member>
								<OutputKey>AwsSecret</OutputKey>
								<OutputValue>W/OCgS7Yw2WixHjrCsTyhU3h+ykLpnBjfWew2zZn</OutputValue>
							</member>
							<member>
								<OutputKey>DynamoReleases</OutputKey>
								<OutputValue>convox-releases</OutputValue>
							</member>
							<member>
								<OutputKey>LogGroup</OutputKey>
								<OutputValue>convox-LogGroup-BVJVTMIP5AKJ</OutputValue>
							</member>
							<member>
								<OutputKey>StackId</OutputKey>
								<OutputValue>arn:aws:cloudformation:us-east-1:778743527532:stack/convox/eb743e00-7d8e-11e5-8280-50ba0727c06e</OutputValue>
							</member>
						</Outputs>
						<Capabilities>
							<member>CAPABILITY_IAM</member>
						</Capabilities>
						<CreationTime>2015-10-28T16:14:09.590Z</CreationTime>
						<NotificationARNs/>
						<StackId>arn:aws:cloudformation:us-east-1:778743527532:stack/convox/eb743e00-7d8e-11e5-8280-50ba0727c06e</StackId>
						<StackName>convox-servicename</StackName>
						<StackStatus>UPDATE_COMPLETE</StackStatus>
						<DisableRollback>false</DisableRollback>
						<Tags/>
						<LastUpdatedTime>2016-08-27T16:29:05.963Z</LastUpdatedTime>
						<Parameters>
							<member>
								<ParameterKey>Tenancy</ParameterKey>
								<ParameterValue>default</ParameterValue>
							</member>
							<member>
								<ParameterKey>Internal</ParameterKey>
								<ParameterValue>No</ParameterValue>
							</member>
							<member>
								<ParameterKey>ApiCpu</ParameterKey>
								<ParameterValue>128</ParameterValue>
							</member>
							<member>
								<ParameterKey>PrivateApi</ParameterKey>
								<ParameterValue>No</ParameterValue>
							</member>
							<member>
								<ParameterKey>ContainerDisk</ParameterKey>
								<ParameterValue>10</ParameterValue>
							</member>
							<member>
								<ParameterKey>SwapSize</ParameterKey>
								<ParameterValue>5</ParameterValue>
							</member>
							<member>
								<ParameterKey>Encryption</ParameterKey>
								<ParameterValue>Yes</ParameterValue>
							</member>
							<member>
								<ParameterKey>Subnet1CIDR</ParameterKey>
								<ParameterValue>10.0.2.0/24</ParameterValue>
							</member>
							<member>
								<ParameterKey>Autoscale</ParameterKey>
								<ParameterValue>No</ParameterValue>
							</member>
							<member>
								<ParameterKey>Version</ParameterKey>
								<ParameterValue>dev</ParameterValue>
							</member>
							<member>
								<ParameterKey>VPCCIDR</ParameterKey>
								<ParameterValue>10.0.0.0/16</ParameterValue>
							</member>
							<member>
								<ParameterKey>Development</ParameterKey>
								<ParameterValue>Yes</ParameterValue>
							</member>
							<member>
								<ParameterKey>ClientId</ParameterKey>
								<ParameterValue>nmert38iwdsrj362jdf</ParameterValue>
							</member>
							<member>
								<ParameterKey>Private</ParameterKey>
								<ParameterValue>No</ParameterValue>
							</member>
							<member>
								<ParameterKey>Subnet2CIDR</ParameterKey>
								<ParameterValue>10.0.3.0/24</ParameterValue>
							</member>
							<member>
								<ParameterKey>Ami</ParameterKey>
								<ParameterValue/>
							</member>
							<member>
						<ParameterKey>InstanceType</ParameterKey>
								<ParameterValue>t2.small</ParameterValue>
							</member>
							<member>
								<ParameterKey>SubnetPrivate1CIDR</ParameterKey>
								<ParameterValue>10.0.5.0/24</ParameterValue>
							</member>
							<member>
								<ParameterKey>VolumeSize</ParameterKey>
								<ParameterValue>50</ParameterValue>
							</member>
							<member>
								<ParameterKey>Password</ParameterKey>
								<ParameterValue>****</ParameterValue>
							</member>
							<member>
								<ParameterKey>ApiMemory</ParameterKey>
								<ParameterValue>128</ParameterValue>
							</member>
							<member>
								<ParameterKey>InstanceUpdateBatchSize</ParameterKey>
								<ParameterValue>1</ParameterValue>
							</member>
							<member>
								<ParameterKey>SubnetPrivate0CIDR</ParameterKey>
								<ParameterValue>10.0.4.0/24</ParameterValue>
							</member>
							<member>
								<ParameterKey>InstanceRunCommand</ParameterKey>
								<ParameterValue/>
							</member>
							<member>
								<ParameterKey>InstanceCount</ParameterKey>
								<ParameterValue>3</ParameterValue>
							</member>
							<member>
								<ParameterKey>SubnetPrivate2CIDR</ParameterKey>
								<ParameterValue>10.0.6.0/24</ParameterValue>
							</member>
							<member>
								<ParameterKey>Subnet0CIDR</ParameterKey>
								<ParameterValue>10.0.1.0/24</ParameterValue>
							</member>
							<member>
								<ParameterKey>ExistingVpc</ParameterKey>
								<ParameterValue/>
							</member>
							<member>
								<ParameterKey>InstanceBootCommand</ParameterKey>
								<ParameterValue/>
							</member>
							<member>
								<ParameterKey>Key</ParameterKey>
								<ParameterValue>convox-keypair-4415</ParameterValue>
							</member>
						</Parameters>
					</member>
				</Stacks>
			</DescribeStacksResult>
			<ResponseMetadata>
				<RequestId>9715cab7-6c75-11e6-837d-ebe72becd936</RequestId>
			</ResponseMetadata>
		</DescribeStacksResponse>`,
	},
}

var cycleServiceDescribeStacks2 = awsutil.Cycle{
	awsutil.Request{"/", "", `Action=DescribeStacks&StackName=servicename&Version=2010-05-15`},
	awsutil.Response{
		200,
		`<DescribeStacksResponse xmlns="http://cloudformation.amazonaws.com/doc/2010-05-15/">
			<DescribeStacksResult>
				<Stacks>
					<member>
						<Outputs>
							<member>
								<OutputKey>CustomTopic</OutputKey>
								<OutputValue>arn:aws:lambda:us-east-1:778743527532:function:convox-CustomTopic-1VJ75T6FBGORL</OutputValue>
							</member>
							<member>
								<OutputKey>Internal</OutputKey>
								<OutputValue>No</OutputValue>
							</member>
							<member>
								<OutputKey>SettingsBucket</OutputKey>
								<OutputValue>convox-settings-c21v4pfz9zpc</OutputValue>
							</member>
							<member>
								<OutputKey>Vpc</OutputKey>
								<OutputValue>vpc-08c5726c</OutputValue>
							</member>
							<member>
								<OutputKey>Dashboard</OutputKey>
								<OutputValue>convox-1423604943.us-east-1.elb.amazonaws.com</OutputValue>
							</member>
							<member>
								<OutputKey>EncryptionKey</OutputKey>
								<OutputValue>arn:aws:kms:us-east-1:778743527532:key/f1752bdd-5805-4891-9208-f16be3a4ccd6</OutputValue>
							</member>
							<member>
								<OutputKey>DockerImageApi</OutputKey>
								<OutputValue>convox/api:20160820033210</OutputValue>
							</member>
							<member>
								<OutputKey>NotificationTopic</OutputKey>
								<OutputValue>arn:aws:sns:us-east-1:778743527532:convox-notifications</OutputValue>
							</member>
							<member>
								<OutputKey>Rack</OutputKey>
								<OutputValue>convox</OutputValue>
							</member>
							<member>
								<OutputKey>Autoscale</OutputKey>
								<OutputValue>false</OutputValue>
							</member>
							<member>
								<OutputKey>AwsRegion</OutputKey>
								<OutputValue>us-east-1</OutputValue>
							</member>
							<member>
								<OutputKey>DynamoBuilds</OutputKey>
								<OutputValue>convox-builds</OutputValue>
							</member>
							<member>
								<OutputKey>Private</OutputKey>
								<OutputValue>No</OutputValue>
							</member>
							<member>
								<OutputKey>Release</OutputKey>
								<OutputValue>20160820033210</OutputValue>
							</member>
							<member>
								<OutputKey>NotificationHost</OutputKey>
								<OutputValue>convox-1423604943.us-east-1.elb.amazonaws.com</OutputValue>
							</member>
							<member>
								<OutputKey>Password</OutputKey>
								<OutputValue>rZPfAaETBaRcmWSYTqulMXcfyXlFlR</OutputValue>
							</member>
							<member>
								<OutputKey>SubnetsPrivate</OutputKey>
								<OutputValue/>
							</member>
							<member>
								<OutputKey>AwsAccess</OutputKey>
								<OutputValue>AKIAIQWYIWCZS6S3K5AA</OutputValue>
							</member>
							<member>
								<OutputKey>Cluster</OutputKey>
								<OutputValue>convox-Cluster-1EQQWK182GWYD</OutputValue>
							</member>
							<member>
								<OutputKey>Provider</OutputKey>
								<OutputValue>aws</OutputValue>
							</member>
							<member>
								<OutputKey>Subnets</OutputKey>
								<OutputValue>subnet-8ea696a5,subnet-95a841e3,subnet-5387870a</OutputValue>
							</member>
							<member>
								<OutputKey>AwsSecret</OutputKey>
								<OutputValue>W/OCgS7Yw2WixHjrCsTyhU3h+ykLpnBjfWew2zZn</OutputValue>
							</member>
							<member>
								<OutputKey>DynamoReleases</OutputKey>
								<OutputValue>convox-releases</OutputValue>
							</member>
							<member>
								<OutputKey>LogGroup</OutputKey>
								<OutputValue>convox-LogGroup-BVJVTMIP5AKJ</OutputValue>
							</member>
							<member>
								<OutputKey>StackId</OutputKey>
								<OutputValue>arn:aws:cloudformation:us-east-1:778743527532:stack/convox/eb743e00-7d8e-11e5-8280-50ba0727c06e</OutputValue>
							</member>
						</Outputs>
						<Capabilities>
							<member>CAPABILITY_IAM</member>
						</Capabilities>
						<CreationTime>2015-10-28T16:14:09.590Z</CreationTime>
						<NotificationARNs/>
						<StackId>arn:aws:cloudformation:us-east-1:778743527532:stack/convox/eb743e00-7d8e-11e5-8280-50ba0727c06e</StackId>
						<StackName>convox</StackName>
						<StackStatus>UPDATE_COMPLETE</StackStatus>
						<DisableRollback>false</DisableRollback>
						<Tags/>
						<LastUpdatedTime>2016-08-27T16:29:05.963Z</LastUpdatedTime>
						<Parameters>
							<member>
								<ParameterKey>Tenancy</ParameterKey>
								<ParameterValue>default</ParameterValue>
							</member>
							<member>
								<ParameterKey>Internal</ParameterKey>
								<ParameterValue>No</ParameterValue>
							</member>
							<member>
								<ParameterKey>ApiCpu</ParameterKey>
								<ParameterValue>128</ParameterValue>
							</member>
							<member>
								<ParameterKey>PrivateApi</ParameterKey>
								<ParameterValue>No</ParameterValue>
							</member>
							<member>
								<ParameterKey>ContainerDisk</ParameterKey>
								<ParameterValue>10</ParameterValue>
							</member>
							<member>
								<ParameterKey>SwapSize</ParameterKey>
								<ParameterValue>5</ParameterValue>
							</member>
							<member>
								<ParameterKey>Encryption</ParameterKey>
								<ParameterValue>Yes</ParameterValue>
							</member>
							<member>
								<ParameterKey>Subnet1CIDR</ParameterKey>
								<ParameterValue>10.0.2.0/24</ParameterValue>
							</member>
							<member>
								<ParameterKey>Autoscale</ParameterKey>
								<ParameterValue>No</ParameterValue>
							</member>
							<member>
								<ParameterKey>Version</ParameterKey>
								<ParameterValue>dev</ParameterValue>
							</member>
							<member>
								<ParameterKey>VPCCIDR</ParameterKey>
								<ParameterValue>10.0.0.0/16</ParameterValue>
							</member>
							<member>
								<ParameterKey>Development</ParameterKey>
								<ParameterValue>Yes</ParameterValue>
							</member>
							<member>
								<ParameterKey>ClientId</ParameterKey>
								<ParameterValue>nmert38iwdsrj362jdf</ParameterValue>
							</member>
							<member>
								<ParameterKey>Private</ParameterKey>
								<ParameterValue>No</ParameterValue>
							</member>
							<member>
								<ParameterKey>Subnet2CIDR</ParameterKey>
								<ParameterValue>10.0.3.0/24</ParameterValue>
							</member>
							<member>
								<ParameterKey>Ami</ParameterKey>
								<ParameterValue/>
							</member>
							<member>
						<ParameterKey>InstanceType</ParameterKey>
								<ParameterValue>t2.small</ParameterValue>
							</member>
							<member>
								<ParameterKey>SubnetPrivate1CIDR</ParameterKey>
								<ParameterValue>10.0.5.0/24</ParameterValue>
							</member>
							<member>
								<ParameterKey>VolumeSize</ParameterKey>
								<ParameterValue>50</ParameterValue>
							</member>
							<member>
								<ParameterKey>Password</ParameterKey>
								<ParameterValue>****</ParameterValue>
							</member>
							<member>
								<ParameterKey>ApiMemory</ParameterKey>
								<ParameterValue>128</ParameterValue>
							</member>
							<member>
								<ParameterKey>InstanceUpdateBatchSize</ParameterKey>
								<ParameterValue>1</ParameterValue>
							</member>
							<member>
								<ParameterKey>SubnetPrivate0CIDR</ParameterKey>
								<ParameterValue>10.0.4.0/24</ParameterValue>
							</member>
							<member>
								<ParameterKey>InstanceRunCommand</ParameterKey>
								<ParameterValue/>
							</member>
							<member>
								<ParameterKey>InstanceCount</ParameterKey>
								<ParameterValue>3</ParameterValue>
							</member>
							<member>
								<ParameterKey>SubnetPrivate2CIDR</ParameterKey>
								<ParameterValue>10.0.6.0/24</ParameterValue>
							</member>
							<member>
								<ParameterKey>Subnet0CIDR</ParameterKey>
								<ParameterValue>10.0.1.0/24</ParameterValue>
							</member>
							<member>
								<ParameterKey>ExistingVpc</ParameterKey>
								<ParameterValue/>
							</member>
							<member>
								<ParameterKey>InstanceBootCommand</ParameterKey>
								<ParameterValue/>
							</member>
							<member>
								<ParameterKey>Key</ParameterKey>
								<ParameterValue>convox-keypair-4415</ParameterValue>
							</member>
						</Parameters>
					</member>
				</Stacks>
			</DescribeStacksResult>
			<ResponseMetadata>
				<RequestId>9715cab7-6c75-11e6-837d-ebe72becd936</RequestId>
			</ResponseMetadata>
		</DescribeStacksResponse>`,
	},
}

var cycleServiceCreateWebhook = awsutil.Cycle{
	awsutil.Request{"/", "", `Action=CreateStack&Capabilities.member.1=CAPABILITY_IAM&Parameters.member.1.ParameterKey=CustomTopic&Parameters.member.1.ParameterValue=&Parameters.member.2.ParameterKey=NotificationTopic&Parameters.member.2.ParameterValue=&Parameters.member.3.ParameterKey=Url&Parameters.member.3.ParameterValue=http%3A%2F%2Fnotifications.example.org%2Fsns%3Fendpoint%3Dhttps%253A%252F%252Fwww.example.com&StackName=convox-mywebhook&Tags.member.1.Key=Name&Tags.member.1.Value=mywebhook&Tags.member.2.Key=Rack&Tags.member.2.Value=convox&Tags.member.3.Key=Service&Tags.member.3.Value=webhook&Tags.member.4.Key=System&Tags.member.4.Value=convox&Tags.member.5.Key=Type&Tags.member.5.Value=service&TemplateBody=%0A%7B%0A++%22AWSTemplateFormatVersion%22+%3A+%222010-09-09%22%2C%0A++%22Parameters%22%3A+%7B%0A++++%22Url%22%3A+%7B%0A++++++%22Type%22+%3A+%22String%22%2C%0A++++++%22Description%22+%3A+%22Webhook+URL%2C+e.g.+%27https%3A%2F%2Fgrid.convox.com%2Frack-hook%2F1234%27%22%0A++++%7D%2C%0A++++%22CustomTopic%22%3A+%7B%0A++++++%22Type%22+%3A+%22String%22%2C%0A++++++%22Description%22+%3A+%22%22%0A++++%7D%2C%0A++++%22NotificationTopic%22%3A+%7B%0A++++++%22Type%22+%3A+%22String%22%2C%0A++++++%22Description%22+%3A+%22%22%0A++++%7D%0A++%7D%2C%0A++%22Resources%22%3A+%7B%0A++++%22Notifications%22%3A+%7B%0A++++++%22Type%22+%3A+%22Custom%3A%3ASNSSubscription%22%2C%0A++++++%22Version%22%3A+%221.0%22%2C%0A++++++%22Properties%22%3A+%7B%0A++++++++%22ServiceToken%22%3A+%7B+%22Ref%22%3A+%22CustomTopic%22+%7D%2C%0A++++++++%22TopicArn%22+%3A+%7B+%22Ref%22%3A+%22NotificationTopic%22+%7D%2C%0A++++++++%22Protocol%22+%3A+%22http%22%2C%0A++++++++%22Endpoint%22+%3A+%7B+%22Ref%22%3A+%22Url%22+%7D%0A++++++%7D%0A++++%7D%0A++%7D%2C%0A++%22Outputs%22%3A+%7B%0A++++%22Url%22%3A+%7B%0A++++++%22Value%22%3A+%7B+%22Ref%22%3A+%22Url%22+%7D%0A++++%7D%0A++%7D%0A%7D%0A&Version=2010-05-15`},
	awsutil.Response{
		200,
		`<CreateStackResponse xmlns="http://cloudformation.amazonaws.com/doc/2010-05-15/">
                                <CreateStackResult>
                                        <StackId>arn:aws:cloudformation:us-east-1:990037048036:stack/` + "mywebhook" + `/cd77a770-7059-11e6-9f55-50fa5f2588d2</StackId>
                                </CreateStackResult>
                                <ResponseMetadata>
                                        <RequestId>cd6fdfe7-7059-11e6-af63-31e395e4ce23</RequestId>
                                </ResponseMetadata>
                        </CreateStackResponse>`,
	},
}
