name: publish
on:
  workflow_dispatch:
    inputs:
        version:
          description: "release version"
          required: true
jobs:
  publish:
    if: github.repository == 'convox/rack'
    environment: 'Publish'
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: golang-1.18
        uses: actions/setup-go@v3
        with:
          go-version: '1.18.10'
      - name: version
        run: echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV
      - name: secrets
        run: ci/secrets.sh
        env:
          SECRETS: ${{ toJson(secrets) }}
      - name: publish the artifacts
        run: ci/publish_arifacts.sh
      - name: publish the release
        run: go run cmd/release/main.go -publish update "${VERSION}"
      - name: notify slack
        run: TYPE=publish ci/slack.sh
