name: release
on:
  workflow_dispatch:
    inputs:
        version:
          description: "release version"
          required: true
jobs:
  release:
    if: github.repository == 'convox/rack'
    environment: 'Publish'
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: golang-1.17
        uses: actions/setup-go@v3
        with:
          go-version: '1.17.13'
      - name: version
        run: echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV
      - name: secrets
        run: ci/secrets.sh
        env:
          SECRETS: ${{ toJson(secrets) }}
      - name: publish the artifacts
        run: ci/publish_arifacts.sh
      - name: publish the release
        run: go run cmd/release/main.go -publish update "${VERSION}"
      - name: copy artifacts to latest
        run: |
          aws s3 cp s3://convox/release/${VERSION}/cli/linux/convox s3://convox/cli/linux/convox --acl public-read
          aws s3 cp s3://convox/release/${VERSION}/cli/linux/convox-arm64 s3://convox/cli/linux/convox-arm64 --acl public-read
          aws s3 cp s3://convox/release/${VERSION}/cli/darwin/convox s3://convox/cli/darwin/convox --acl public-read
          aws s3 cp s3://convox/release/${VERSION}/cli/darwin/convox-arm64 s3://convox/cli/darwin/convox-arm64 --acl public-read
          aws s3 cp s3://convox/release/${VERSION}/cli/windows/convox.exe s3://convox/cli/windows/convox.exe --acl public-read
      - name: notify slack
        run: TYPE=publish ci/slack.sh
